---
output:
  word_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

# Chance's Second Thesis Chapter: Understand Thermal Niche from Consumption TPCs

Made by Chance Yan Last Edit: 1/4/26

**Question:** Is there thermal niche overlap or complementary in consumption among the predatory crabs of the Gulf of Maine?

**Hypothesis:** There is thermal niche complementary between the crab predators. 

**Null Hypothesis:** There is thermal niche overlap between the crab predators.

**Predictions:**

-   Prediction 1: The Asian shore crab will have the highest consumption TPC/thermal niche compared to green crabs and cancer crabs. Followed by green crabs having the second highest TPC/thermal niche. Meanwhile, cancer crabs (*Cancer borealis* preferred, but *Cancer irroratus* backup - more on this later)

-   Prediction 2:There is no difference in consumption TPC between green crabs, Asian shore crabs, and cancer crabs. 

-   Prediction 3: There is some overlap between 2 of the species, but not the last one. 

**Experimental Design:**

2 Systems (2 possible temperatures at a time), 5 temperature regimes (minimum to map out a TPC), 3 species, 6 repetitions. We can only fit 18 individuals in each system.

6 reps \* 3 species \* 5 temperature regimes \* 2 temporal blocks = 180 crabs\

**Methods**

Crabs were collected and brought into GMS via SCUBA, intertidally, or trapping. Only males with 2 or less missing legs were used in the study. Upon entry into the lab, crabs were weight and carapace length was measured. Crabs were placed into 5 gallon buckets in a wet table with a recirculating seawater system. Each were supplied with a water line and air line. There were two wet tables for one system which was set to one temperature treatment. The temperature treatments were 18, 20, 22, 24, and 26 degrees Celcius.

Crabs were fed 3 times a week with clam and squid in an alternating pattern. Crabs were acclimated for the trial temperature for two weeks and fed an additional 3 times for the feeding trial.

## Data Processing

```{R, include = FALSE, warning = FALSE}
library(ggplot2)
library(lubridate)
library(hms)
library(dplyr)
library(emmeans)
library(knitr)
library(brglm)
library(glmmTMB)
library(DHARMa)
library(MuMIn)
library(glmm)
library(lmerTest)
library(mgcv)
library(ggplot2)
library(mgcViz)
library(gratia)
setwd("/Users/chanceyan/Documents/R/ThesisCrab/Data")
crabdata <- read.csv("Feeding.csv", h=T, stringsAsFactors = FALSE)
death <- read.csv("DeathCount.csv", h=T, stringsAsFactors = FALSE)
master <- read.csv("Master.csv", h=T, stringsAsFactors = FALSE)
deathMeta <- read.csv("Death.csv", h=T, stringsAsFactors = FALSE)
husbandry <- read.csv("Husbandry.csv", h=T, stringsAsFactors = FALSE)
checkout <- read.csv("CheckOut.csv", h=T, stringsAsFactors = FALSE)
```

#### Cleaning up data for use

We need to clean up the data first to use it. What I did...

NOTE: "feeding points" refer to a measurement of feeding. Therefore we have multiple feeding points from a single individual crab.

-   Removed feeding points that used mussels and mackerel. We fed two days total of mussels and mackerel to find out that it was too difficult to measure accurately. Afterwards, we switched to Clam and Squid in an alternating pattern
-   I then removed those who molted (removed as in removed all feeding points that individual contributed to the dataset) as molting has been shown in the literature to affect feeding rate.
-   I removed the first week and first period of feeding from Trial 18 and 22 since they were fed two days in a row (accidentally + understanding methods). They still had 3 weeks of feeding (2 weeks of acclimation similar to the other trials).
-   I removed feeding points for those who ate everything that we fed them. This is because it's possible they could have eaten more and the point becomes inaccurate.
-   Very rarely (around 4-5 times total), food would be found floating in the bucket after waiting the feeding period. I have removed these feeding points as well because the crab couldn't get to the food and eat for the feeding period and therefore the point cannot be trusted
-   The rest of the code is marking individuals if they've eaten or not, still eaten, making extra variables so that further analyses are easier.

```{R include = FALSE, warning = FALSE}
#removing rows that contain no data or recorded incorrectly
for(i in 1:nrow(crabdata)){
  if(!is.numeric(crabdata[i,4])){
    print(crabdata[i])
    crabdata <- crabdata[-i,]
  }
  if(!is.numeric(crabdata[i,6])){
    print(crabdata[i])
    crabdata <- crabdata[-i,]
  }
}

#Creating number IDs for each crab based of their IDs so it's easier to loop through with future code. Also I'm adding a total eaten by proportion column, so we have a standard metric to compare by.
for(i in 1:36){
  master$num[[i]] <- substr(master$ID[[i]], 3,5)
}

crabdata$amount.eaten <- crabdata$FoodIn-crabdata$FoodOut
all <- merge(crabdata, master, by="ID")

#renaming temperature.x to temperature
all <- all %>% dplyr::select(-Temperature.y)
names(all)[names(all) == "Temperature.x"] <- "Temperature"

#Changing date column into a date data type, so that R can read it as a Date.
all$Date.x = as.Date(all$Date.x, format = "%m/%d/%Y")
deathMeta$Date = as.Date(deathMeta$Date, format = "%m/%d/%Y")

#removing mussel and mackerel feed
all <- subset(all, all$Food != "Mussels")
all <- subset(all, all$Food != "Mackerel")


#saving those who molted in an original dataset
original_molted <- all
original_molted$molted <- ifelse(grepl("ME", original_molted$Notes.x, fixed = TRUE), "YES", "NO")

#Removing those that molted
array <- c()

for(i in 1:nrow(all)){
  if(grepl("ME", all$Notes.x[i], fixed = TRUE)){
    ID_value <- all$ID[i]
    for(j in 1:nrow(all)){
      if(all$ID[j] == ID_value){
        array <- c(array, j)
      }
    }
  }
}

all <- all[-array,]
array <- c()

#Removing these dates because feeding was not following a strict schedule (fed two days back to back)
all <- subset(all, !(WeekNum == 1 & Temperature == 16))
all <- subset(all, !(WeekNum == 1 & Temperature == 22 & Period == 1))

#Changing trials 16 and 18 to be one.
original <- all
all$Temperature <- ifelse(all$Temperature == 16, 18, all$Temperature)
original$Temperature <- ifelse(original$Temperature == 16, 18, original$Temperature)
master$Temperature <- ifelse(master$Temperature == 16, 18, master$Temperature)

#Here, I am marking all those who did not eat
EatDF <- subset(all, grepl("DE", all$Notes.x, fixed = TRUE))

#removing all those who ate everything
all <- all[ !grepl("AE", all$Notes.x), ]

#removing all those who were found to have floating food
all <- all[ !grepl("FLOAT", all$Notes.x), ]

#Making a new column indicating whether the animal ate or not
eaten_row <- list()
for(i in 1:nrow(all)){
  if(grepl("DE", all$Notes.x[i], fixed = TRUE)){
    eaten_row <- c(eaten_row, "NO")
  }
  else{
    eaten_row <- c(eaten_row, "YES")
  }
}
all$eaten <- eaten_row

#Making a column if the animal was still eating or not
all$still_eating <- ifelse(grepl("SE", all$Notes.x, fixed = TRUE), "YES", "NO")

inBucket <- list()
#total time of food in bucket
all$TimeInStrip <- as.POSIXct(paste(all$Date.x, all$TimeIn), format = "%Y-%m-%d %I:%M:%S %p")
all$TimeOutStrip <- as.POSIXct(paste(all$Date.x, all$TimeOut), format = "%Y-%m-%d %I:%M:%S %p")

#because we removed the first week from trials 1 and 2, to get the final week, I'll just subtract one from the value to line it up so that week 4 equals week 3 and make it easier for me to graph

all$WeekNum <- ifelse((all$Temperature == 18 & all$WeekNum == 2 & all$Period == 1), 1, all$WeekNum)
all$WeekNum <- ifelse((all$Temperature == 18 & all$WeekNum == 3 & all$Period == 1), 2, all$WeekNum)
all$WeekNum <- ifelse((all$Temperature == 18 & all$WeekNum == 4 & all$Period == 1), 3, all$WeekNum)

all$WeekNum <- ifelse((all$Temperature == 22 & all$WeekNum == 2 & all$Period == 1), 1, all$WeekNum)
all$WeekNum <- ifelse((all$Temperature == 22 & all$WeekNum == 3 & all$Period == 1), 2, all$WeekNum)
all$WeekNum <- ifelse((all$Temperature == 22 & all$WeekNum == 4 & all$Period == 1), 3, all$WeekNum)

#making a new ID for those that are placements
all$ID <- ifelse(grepl("RE", all$Notes.x), paste(all$ID, "R"), all$ID)

#husbandry sheet prep
husbandry <- subset(husbandry, husbandry$Temperature != "NONE")   
```

We have some decisions to make, but we'll boil it down to the all-inclusive model vs the censoring model

All-inclusive model:

-Add in all those who died as zeros and even beyond after they died they still remain as 0's.

-Also keep in replacement data.

-Keep crabs who died as is in the data set

Censoring model:

-Remove feeding points from all those who died and those who were replacement.

-Turn all the feeding points of those who did not eat to 0

-Remove dead individual

ALL-INCLUSIVE MODEL:

-Includes all those who died, data points after they've died becomes 0

-Induces those that were replaced as well

-We had an extra cancer crab replacement at the time when CI44 died, so we replaced the crab before the trial started, hence removal of the extra individuals. I renamed all the replacements to have the original replaced crab ID and "R" to note that it was a replacement therefore, CI44 R is really just CI44. Which I changed below.

```{R}
inclusive <- all

inclusive$proportion.eaten <- inclusive$amount.eaten / inclusive$WW
inclusive <- subset(inclusive, !is.na(inclusive$proportion.eaten))

inclusive <- subset(inclusive, inclusive$ID != "CI44")
inclusive$ID <- ifelse(inclusive$ID == "CI44 R", "CI44", inclusive$ID)

hold <- subset(all, all$amount.eaten < 0)

length(unique(inclusive$ID))
```

CENSORING MODEL:

-Removes those who died completely and those who were used to be replaced.

-Sets those who didn't eat to 0 (for feeding points)

```{R}
censor <- all

censor$amount.eaten <- ifelse(grepl("DE", censor$Notes.x, fixed = TRUE), 0, censor$amount.eaten)
censor$amount.eaten <- ifelse(censor$amount.eaten < 0, 0, censor$amount.eaten)

censor <- censor[is.na(censor$Date.x) | !(censor$ID %in% deathMeta$ID),]


censor <- censor %>%dplyr::filter(!grepl("DI", Notes.x))
censor <- censor %>%dplyr::filter(!grepl("ADDI", Notes.x))
censor <- censor %>%dplyr::filter(!grepl("RE", Notes.x))
censor <- censor %>%dplyr::filter(!grepl("molted", Notes.x))

list <- c("DI", "ADDI", "RE", "molted")

removed <- censor %>%
  dplyr::filter(grepl(paste(list, collapse = "|"), Notes.x))

removed <- censor %>%dplyr::filter(grepl("DI", Notes.x))
unique(removed$ID)

censor$proportion.eaten <- censor$amount.eaten / censor$WW
censor <- subset(censor, !is.na(censor$proportion.eaten))

length(unique(censor$ID))
```

### Basic information on the dataset (Post Data Modifications)

```{r echo = FALSE, warning = FALSE}
#inclusive model
a <- tapply(inclusive$ID, list(inclusive$Species.x, inclusive$Temperature), FUN = function(x) length(unique(x)))
b <- tapply(inclusive$proportion.eaten, list(inclusive$Species.x, inclusive$Temperature), FUN = length)

#censor model
d <- tapply(censor$ID, list(censor$Species.x, censor$Temperature), FUN = function(x) length(unique(x)))
e <- tapply(censor$proportion.eaten, list(censor$Species.x, censor$Temperature), FUN = length)

kable(rbind(Inclusive = a, Censor = d), caption = "Inclusive on top, Censor on the bottom. Number of Individuals")
kable(rbind(Inclusive = b, Censor = e), caption = "Inclusive on top, Censor on the bottom. Number of Feeding Points")
```

### Dead or alive: Are there differences in the amount of alive/dead individuals as temperature increases? Which species out of the three is this relationship the strongest?

What I did:

-I added the extras on the master data frame which contains all individuals who were ever in the systems that are included in the project

-I then created two exploratory graphs to represent how the data looks in general

\- NOTE - a good model should show that there is a decrease in alive individuals as temperature increases for the Rock Crab. Green crabs and shore crabs should remain relatively flat (no increase death with temperatures)

-To account for the separated data I will use a bias reduced GLM. Following code from: <https://bscheng.com/2016/12/11/modeling-completely-separated-data-in-r/>

-I then fit the model to an all mod (all explanatory variables added with interactions). Then dredged the model to see which model is the "best"

-The best model came back as one that included temperature and Species (all explanatory variables); however, without interactions

-Best model \<- dead \~ Temperature (numeric) + Species (factor)

-This best model summary tells us there are differences in the INTERCEPTS between green crabs/shore crabs and rock crabs. The model also indicates that there is a slope that is negative for ALL species. This is because we did not include an interaction (including an interaction makes the model find no differences and AIC finds no interaction model a worse one)

-Since it seems obvious that rock crabs are doing worse than green crabs and shore crabs (a little disappointed it didn't pick it up), I modeled with just rock crab data

-I modeled just rock crab data and found that there was a significantly negative slope as temperature increases.

Summary: I modeled dead and alive crabs using a bias reduced GLM. After dredging the best model was a full additive model (temperature and species); however, the model dictates all species have the same slope (decrease of alive individuals across temperature) and therefore I modeled just rock crabs to see a negative slope (decrease in alive individuals)

```{R echo=FALSE, warning=FALSE, message = FALSE}
original_master <- master

#Hemi that died by human cause not natural
master <- subset(master, master$ID != "HS155")
#parsing between those who died during the experiment and those who lived
master$dead <- ifelse(master$ID %in% deathMeta$ID, 0, 1)	

#addition of extras
{
add_rows <- data.frame(ID = "extra1_26", System = NA, CL = NA, WW = NA, Temperature = 26, Species = "Irroratus", Condition = NA, Period = NA, Date = NA, Notes = NA, num = NA, dead = 0)
master <- rbind(master, add_rows)
add_rows <- data.frame(ID = "extra2_26", System = NA, CL = NA, WW = NA, Temperature = 26, Species = "Irroratus", Condition = NA, Period = NA, Date = NA, Notes = NA, num = NA, dead = 0)
master <- rbind(master, add_rows)
add_rows <- data.frame(ID = "extra1_24", System = NA, CL = NA, WW = NA, Temperature = 24, Species = "Irroratus", Condition = NA, Period = NA, Date = NA, Notes = NA, num = NA, dead = 0)
master <- rbind(master, add_rows)
add_rows <- data.frame(ID = "extra2_24", System = NA, CL = NA, WW = NA, Temperature = 24, Species = "Irroratus", Condition = NA, Period = NA, Date = NA, Notes = NA, num = NA, dead = 1)
master <- rbind(master, add_rows)
add_rows <- data.frame(ID = "extra1_22", System = NA, CL = NA, WW = NA, Temperature = 22, Species = "Irroratus", Condition = NA, Period = NA, Date = NA, Notes = NA, num = NA, dead = 1)
master <- rbind(master, add_rows)
add_rows <- data.frame(ID = "extra2_22", System = NA, CL = NA, WW = NA, Temperature = 22, Species = "Irroratus", Condition = NA, Period = NA, Date = NA, Notes = NA, num = NA, dead = 1)
master <- rbind(master, add_rows)
add_rows <- data.frame(ID = "extra1_20", System = NA, CL = NA, WW = NA, Temperature = 20, Species = "Irroratus", Condition = NA, Period = NA, Date = NA, Notes = NA, num = NA, dead = 1)
master <- rbind(master, add_rows)
add_rows <- data.frame(ID = "extra2_20", System = NA, CL = NA, WW = NA, Temperature = 20, Species = "Irroratus", Condition = NA, Period = NA, Date = NA, Notes = NA, num = NA, dead = 1)
master <- rbind(master, add_rows)
add_rows <- data.frame(ID = "extra1_18", System = NA, CL = NA, WW = NA, Temperature = 18, Species = "Irroratus", Condition = NA, Period = NA, Date = NA, Notes = NA, num = NA, dead = 1)
master <- rbind(master, add_rows)
add_rows <- data.frame(ID = "extra2_18", System = NA, CL = NA, WW = NA, Temperature = 18, Species = "Irroratus", Condition = NA, Period = NA, Date = NA, Notes = NA, num = NA, dead = 1)
master <- rbind(master, add_rows)
}

mastergraph <-  master %>%
  count(Species, Temperature, dead) %>%
  group_by(Species, Temperature) %>%
  mutate(
    proportion = n / sum(n)
  )

mastergraph$dead <- factor(mastergraph$dead, levels = c(1,0))

ggplot(mastergraph, aes(x = Temperature, y = proportion, fill = dead)) + geom_col() + facet_wrap(~Species)+
  scale_fill_manual(values = c("0" = "darkred", "1" = "darkgreen")) + ggtitle("Proportion of crab deaths across temperature")

mastergraph <- master
mastergraph$dead <- factor(mastergraph$dead, levels = c(0,1))

ggplot(mastergraph, aes(x = Temperature, y = dead, color = Species)) + geom_point(position = position_jitter(height = 0.1, width = 0.25)) +
  xlab("Temperature (°C)")+
  ylab("")+
  facet_wrap(~Species, labeller = as_labeller(c("Carcinus" = "Green Crab", "Hemigrapsus" = "Asian Shore Crab", "Irroratus" = "Rock Crab")))+
  ggtitle("Crab Survival") + 
  scale_color_manual(values = c("Carcinus" = "darkgreen",
                                    "Hemigrapsus" = "darkred",
                                    "Irroratus" = "darkorange"), labels = c("Green Crab", "Asian Shore Crab", "Rock Crab")) + theme_classic() +
    theme(plot.title = element_text(size = 15, face = "bold", hjust = 0.5)) +
  theme(legend.position = "none") +
  scale_x_continuous(breaks = c(18, 20, 22, 24, 26)) +
  scale_y_discrete(labels = c("1" = "Alive", "0" = "Dead"),breaks = c(0,1))
  

dat <- subset(mastergraph, mastergraph$Species == "Irroratus" & mastergraph$Temperature == 22 & mastergraph$dead == 0)
nrow(dat)

```

After the exploratory graphs, we should have a model that suggests no change across species and an increase in rock crab deaths as temperature increases. I'll try dredging the full model with Temperature and species. This is the best model summary output.

```{R echo=FALSE, warning=FALSE, message = FALSE}
#using 
all.mod <- brglm(dead ~ Temperature*Species, family = binomial, data = master, na.action = "na.fail")
#dredge(all.mod, rank = "AICc")

#the best mod is inclusion of Species and Trial with no interaction
best.mod <- brglm(dead ~ Temperature + Species, family = binomial, data = master, na.action = "na.fail")
summary(best.mod)
summary(all.mod)
#what's the best way to create diagnostic plots for this?

master$Species <- factor(master$Species)
newdat <- expand.grid(Temperature = seq(min(master$Temperature), max(master$Temperature), length.out = 100), Species = levels(master$Species))
newdat$Species <- factor(newdat$Species, levels = levels(master$Species))

newdat$pred <- predict(best.mod, newdata = newdat, type = "response")

ggplot(master, aes(x = Temperature, y = dead, color = Species)) +
  geom_point(position = position_jitter(height = 0.05), alpha = 0.6) +
  geom_line(data = newdat, aes(x = Temperature, y = pred, color = Species), linewidth = 1) +
  scale_y_continuous(limits = c(0, 1)) + 
  ggtitle("Predicted number of dead (0) vs alive (1) crabs") + 
  scale_color_manual(values = c("Carcinus" = "darkgreen",
                                "Hemigrapsus" = "darkred",
                                "Irroratus" = "darkorange"))
```

That model doesn't really describe that the shore crab and green crab rate are 0. The general temperature variable is across the whole data set and not species specific. I can tell based off the raw data that there are only two death points for green crabs and zero for shore crab. Therefore it might not be necessary to model them. Instead, here I'll just model rock crabs. The following is the best rock crab model summary and the predicted values

```{R echo=FALSE, warning=FALSE, message = FALSE, fig.width=7, fig.height=5}

citation("brglm")
#just Cancer irroratus
holddf <- subset(master, master$Species == "Irroratus")
all.mod <- brglm(dead ~ Temperature, family = binomial, data = holddf, na.action = "na.fail")
#dredge(all.mod, rank = "AICc")
best.mod <- brglm(dead ~ Temperature, family = binomial, data = holddf, na.action = "na.fail")
summary(best.mod)

newdat <- data.frame(Temperature = seq(min(holddf$Temperature), max(holddf$Temperature), length.out = 100))

newdat$pred <- predict(best.mod, newdata = newdat, type = "response")

pred_link <- predict(
  best.mod,
  newdata = newdat,
  type = "link",
  se.fit = TRUE
)

newdat$fit <- pred_link$fit
newdat$se  <- pred_link$se.fit

newdat$lwr <- plogis(newdat$fit - 1.96 * newdat$se)
newdat$upr <- plogis(newdat$fit + 1.96 * newdat$se)
newdat$pred <- plogis(newdat$fit)

ggplot(holddf, aes(x = Temperature, y = dead)) +
  geom_point(
    position = position_jitter(height = 0.05),
    alpha = 0.6,
    color = "darkorange"
  ) +
  geom_ribbon(
    data = newdat,
    aes(x = Temperature, ymin = lwr, ymax = upr),
    fill = "darkorange",
    alpha = 0.25,
    inherit.aes = FALSE
  ) +
  geom_line(
    data = newdat,
    aes(x = Temperature, y = pred),
    linewidth = 1,
    color = "darkorange"
  ) +
  xlab("Temperature (°C)") +
  ylab("Percentage Alive") +
  ggtitle("Predicted number of dead vs alive Atlantic rock crabs") +
  theme_classic() +
  theme(
    plot.title = element_text(size = 15, face = "bold", hjust = 0.5)
  ) +
  scale_x_continuous(breaks = c(18, 20, 22, 24, 26)) +
  scale_y_continuous(
    limits = c(0, 1),
    breaks = c(0, 0.25, 0.5, 0.75, 1),
    labels = scales::percent_format(accuracy = 1)
  )

#---------------

# First, build newdat for Irroratus only (your existing model code stays the same)
holddf <- subset(master, master$Species == "Irroratus")
best.mod <- brglm(dead ~ Temperature, family = binomial, data = holddf, na.action = "na.fail")
summary(best.mod)

newdat <- data.frame(Temperature = seq(min(holddf$Temperature), max(holddf$Temperature), length.out = 100))
pred_link <- predict(best.mod, newdata = newdat, type = "link", se.fit = TRUE)
newdat$fit <- pred_link$fit
newdat$se  <- pred_link$se.fit
newdat$lwr <- plogis(newdat$fit - 1.96 * newdat$se)
newdat$upr <- plogis(newdat$fit + 1.96 * newdat$se)
newdat$pred <- plogis(newdat$fit)

# Add Species column so facet_wrap knows which panel to draw it in
newdat$Species <- "Irroratus"
mastergraph$dead <- as.numeric(as.character(mastergraph$dead))

mastergraph$Species <- factor(mastergraph$Species, levels = c("Hemigrapsus", "Carcinus", "Irroratus"))
newdat$Species <- factor(newdat$Species, levels = c("Hemigrapsus", "Carcinus", "Irroratus"))

ggplot(mastergraph, aes(x = Temperature, y = dead, color = Species)) +
  geom_point(position = position_jitter(height = 0.05, width = 0.25), , alpha = 0.5) +
  geom_line(
    data = newdat,
    aes(x = Temperature, y = pred),
    linewidth = 1,
    color = "darkorange"
  )+
  geom_ribbon(
    data = newdat,
    aes(x = Temperature, ymin = lwr, ymax = upr),
    fill = "darkorange",
    alpha = 0.25,
    inherit.aes = FALSE
  )  +
  xlab("Temperature (°C)") +
  ylab("") +
  facet_wrap(~Species, labeller = as_labeller(c(
    "Hemigrapsus"  = "Asian Shore Crab",
    "Carcinus"     = "Green Crab",
    "Irroratus"    = "Rock Crab"
  ))) +
  ggtitle("Crab Survival") +
  scale_color_manual(
    values = c("Hemigrapsus" = "darkred", "Carcinus" = "darkgreen", "Irroratus" = "darkorange"),
    labels = c("Asian shore Crab", "Green Crab", "Rock Crab")
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 15, face = "bold", hjust = 0.5),
    legend.position = "none"
  ) +
  scale_x_continuous(breaks = c(18, 20, 22, 24, 26))+
  scale_y_continuous(
  limits = c(-0.1, 1.1),
  breaks = c(0, 1),
  labels = c("Dead", "Alive")
)
```

### Acclimation: Are there differences in proportion eaten across week number for each species, temperature regime and time period?

#### Exploratory Graphs:

-I started by graphing what we would expect the acclimation models to suggest.

-If acclimation worked, we should expect an increase or decrease in the first week to the second then it should hit a flat line (indicating no change in consumption) going from week 2 to 3. That would indicate 2 weeks of acclimation is sufficient for measuring consumption

-I summarized the mean and standard error for each species, temperature and period then graphed the proportion consumed over week number to test if the acclimation worked. I also compared these graphs between the censor model and inclusive model

-I found very little differences (visually) between the inclusive and censor model

-It seems like there are very little differences between all weeks for rock crabs and green crabs; however, we do see some differences in shore crabs between the week numbers. Hopefully our model reflects this.

#### Modeling Acclimation:

-Each species was modeled separately as we are only interested in if the acclimation time was sufficient (i.e. consumption rate is stable after two weeks of acclimation)

-Further, each temperature was modeled independently of each other because we do not care about differences among different temperature treatments.

-I started by graphing out response variables for each species. Green crabs and shore crabs seem to be relatively normal while rock crabs have some potential weirdness.

-For each species, I tested which model worked best for temperature treatment 18 and then applied that model to the rest of the temperature treatments and checked for fit

#### Model Fits:

-Green crabs: Their response variable was mainly normal, so I started by using a GLM with a family of gaussian. After checking the diagnostics, the models seem to be a good fit across all temperature treatments

-Shore crabs: The previous steps were repeated and I found the model fit was ok for all the temperature treatments (family = gaussian)

-Rock crabs: The typically normal GLM did not fit well for these crabs. I tried other models such as Gamma; however, found poor fit in all. Even transforming the data did not work. I then decided to model it with zero-inflation as I noticed in the graphs there was a large group surrounding zero. Modeling with zero-inflation provided a strong fit for all temperature treatments; however, for temperature treatment 20 I fitted a zero-inflated gaussian model rather than a Gamma model (which are the rest) since the distribution of the response variable was normal and the model was a better fit then a Gamma for 20 C temperature treatment.

#### Pairwise comparisons (RESULTS FOR ACCLIMATION):

-I then made pairwise comparisons between each week number for all species and temperature treatments.

-Reminder: We are looking for differences between week number 2 and 3. If there are no differences this will indicate consumption has flattened and stablized. If not, then feeding may potentially continue to increase or decrease.

-Green crabs: No differences between any groups

-Shore crabs: some temperature treatments have differences between groups (importantly between week 2 and 3). The only temperature treatments where we see differences between week 2 and 3 are temperature treatments 22C and 24C

Additional note for shore crabs: Both differences between week 2 and 3 for temperature treatments 22 C and 24 C are always decrease from week 2 to 3 (week 3 is always smaller amount) - as noted before this may be a saturation effect. Crabs are eating more than enough and therefore will opt out of feeding more in future feedings.

-Rock crabs: No differences between week 2 and 3 for all temperature treatments, but some have differences between week 1 and 3

TLDR: I first made exploratory graphs, then modeled each species and temperature treatment separately. I used GLMs for shore and green crabs while I used zero-inflated models for rock crabs. All models fit well and the only difference between week 2 and 3 consumption rate lies within temperature treatment 22C and 24 C for shore crabs.

```{R echo=FALSE, warning=FALSE, message = FALSE, fig.width=7, fig.height=5}
summary_inclusive <- inclusive %>%
  group_by(Species.x, Temperature, Period, WeekNum) %>%
  summarise(
    mean = mean(proportion.eaten),
    se = sd(proportion.eaten) / sqrt(n())
  )

summary_inclusive$SpeciesPeriod <- paste(summary_inclusive$Species.x, summary_inclusive$Period, sep = "_")

summary_censor <- censor %>%
  group_by(Species.x, Temperature, Period, WeekNum) %>%
  summarise(
    mean = mean(proportion.eaten),
    se = sd(proportion.eaten) / sqrt(n())
  )

summary_censor$SpeciesPeriod <- paste(summary_censor$Species.x, summary_censor$Period, sep = "_")

#INCLUSIVE MODEL
ggplot(summary_inclusive, aes(x = as.numeric(WeekNum), y = mean, color = SpeciesPeriod)) + 
  geom_point(position = position_dodge(width = 0.2)) + 
  facet_wrap(~as.factor(Temperature)) +
  ggtitle("Proportion consumed over week number for the inclusive model") + 
  geom_smooth(method = "loess", se = FALSE)+
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), position = position_dodge(width = 0.2))+
  scale_color_manual(values = c("CI_1" = "darkorange3",
                     "CI_2" = "orange",
                     "CM_1" = "darkgreen",
                     "CM_2" = "green3",
                     "HS_1" = "darkred",
                     "HS_2" = "red3"),
                     labels = c("CI_1" = "Period 1 Rock Crab",
                                "CI_2" = "Period 2 Rock Crab",
                                "CM_1" = "Period 1 Green Crab",
                                "CM_2" = "Period 2 Green Crab",
                                "HS_1" = "Period 1 Asian Shore Crab",
                                "HS_2" = "Period 2 Asian Shore Crab"),
                     name = "Species/Period")+
  theme(plot.title = element_text(size = 15, face = "bold", hjust = 0.5)) +
  xlab("Week Number")+
  scale_x_continuous(breaks = c(1, 2, 3))+
  ylab("Average proportion of body weight eaten (%)")

#CENSOR MODEL
ggplot(summary_censor, aes(x = as.numeric(WeekNum), y = mean, color = SpeciesPeriod)) + 
  geom_point(position = position_dodge(width = 0.2)) + 
  facet_wrap(~as.factor(Temperature)) +
  ggtitle("Proportion consumed over week number for the censor model") + 
  geom_smooth(method = "loess", se = FALSE)+
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), position = position_dodge(width = 0.2))+
  scale_color_manual(values = c("CI_1" = "darkorange3",
                     "CI_2" = "orange",
                     "CM_1" = "darkgreen",
                     "CM_2" = "green3",
                     "HS_1" = "darkred",
                     "HS_2" = "red3"),
                     labels = c("CI_1" = "Period 1 Rock Crab",
                                "CI_2" = "Period 2 Rock Crab",
                                "CM_1" = "Period 1 Green Crab",
                                "CM_2" = "Period 2 Green Crab",
                                "HS_1" = "Period 1 Asian Shore Crab",
                                "HS_2" = "Period 2 Asian Shore Crab"),
                     name = "Species/Period")+
  theme(plot.title = element_text(size = 15, face = "bold", hjust = 0)) +
  xlab("Week Number")+
  scale_x_continuous(breaks = c(1, 2, 3))+
  ylab("Average proportion of body weight eaten (%)")

summary_censor <- censor %>%
  group_by(Species.x, Temperature, Period) %>%
  summarise(
    mean = mean(proportion.eaten),
    se = sd(proportion.eaten) / sqrt(n())
  )

ggplot(summary_censor, aes(x = Temperature, y = mean, group = as.factor(Period), color = as.factor(Period))) + 
         geom_point(position = position_dodge(width = 0.2)) +
         facet_wrap(~Species.x)+ 
  geom_line(position = position_dodge(width = 0.2))+
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), position = position_dodge(width = 0.2)) + labs(color = "Period") +ylab("Proportion Eaten") + xlab("Temperature") + theme_classic()+
  scale_color_manual(values = c("1" = "darkblue", "2" = "purple"))

#going forward, I'll do data exploration with the censor model since the graphs looked very similar.

#both response variables are skewed
hist(censor$proportion.eaten, main = "Distribution of the censor model", xlab = "Proportion Eaten")
hist(inclusive$proportion.eaten, main = "Distribution of the inclusive model", xlab = "Proportion Eaten")

#"We assume that the error terms, and the observations, within each group come from normally distributed populations ... in each group"
#I need to test normality within group
ggplot(censor, aes(y = proportion.eaten, fill = Species.x)) + geom_boxplot() + 
  scale_fill_manual(values = c("CI" = "darkorange",
                    "CM" = "darkgreen",
                    "HS" = "darkred")) + ggtitle("Boxplot of Censor Model")

ggplot(censor, aes(x = proportion.eaten, fill= Species.x)) + geom_histogram()+ 
  scale_fill_manual(values = c("CI" = "darkorange",
                    "CM" = "darkgreen",
                    "HS" = "darkred")) + facet_wrap(~Species.x, scales = "free") + ggtitle("Histogram of Censor Model")

ggplot(inclusive, aes(y = proportion.eaten, fill = Species.x)) + geom_boxplot() + 
  scale_fill_manual(values = c("CI" = "darkorange",
                    "CM" = "darkgreen",
                    "HS" = "darkred")) + ggtitle("Boxplot of Inclusive Model")

ggplot(inclusive, aes(x = proportion.eaten, fill= Species.x)) + geom_histogram()+ 
  scale_fill_manual(values = c("CI" = "darkorange",
                    "CM" = "darkgreen",
                    "HS" = "darkred")) + facet_wrap(~Species.x, scales = "free")+ ggtitle("Histogram of Inclusive Model")
```

Both models look similar so I'll do analysis exploration with the censor model and compare towards the end.

I'll be modeling each species independently since I am interested in how each species responds on their own and not differences between other species (I want to know if acclimation worked or not so it doesn't involve other species) Further, I want to understand how each week number differs WITHIN temperature. Therefore, it is probably best to model each temperature on their own NOTE: Temperature is being taken as a factor here since we only care about within temperature treatments! I'll only be using the censor model since it lacks negatives and it's easier to handle. Also, preliminary graphs suggests data is very similar and both aren't needed for all comparisons (I will compare final models) Week number will be used as a factor since we care about direct differences between week 1 and 3 not just if it increases across the weeks We'll use a GLM and add, Week number as the only explanatory variable. We'll model specific temperatures and species on their own.

Let's begin with green crabs since they are normal and "easier" to handle. In this next section, you'll see the diagnostic plots and then the following is the model summary (to parse differences).

```{R echo=FALSE, warning=FALSE, message = FALSE, fig.width=7, fig.height=5}
#GREEN CRABS------------------------------------------------------------------------
library(tidyr)
par(mfrow=c(2,2))

#Temperature 18 - #No differences between week numbers and model fits well
censorsub <- subset(censor, censor$Species.x == "CM" & censor$Temperature == 18)
mod <- glm(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = censorsub)
plot(mod, main = "18C, diagnostic plots for CM")
summary(mod)
emm <- emmeans(mod, ~as.factor(WeekNum) | as.factor(Period))
pairs_res_18 <- pairs(emm, adjust = "tukey")
pvals_df_18 <- as.data.frame(pairs_res_18)
pvals_df_18$contrast <- as.character(pvals_df_18$contrast)

pvals_df_18 <- pvals_df_18 %>%
    separate(contrast, into = c("comp1", "comp2"), sep = " - ")

pvals_df_18$Temperature <- as.factor(18)


#Temperature 20 - #No differences between week numbers and model fits well
censorsub <- subset(censor, censor$Species.x == "CM" & censor$Temperature == 20)
mod <- glm(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = censorsub)
plot(mod, main = "20C, diagnostic plots for CM")
summary(mod)
emm <- emmeans(mod, ~as.factor(WeekNum) | as.factor(Period))
pairs_res_20 <- pairs(emm, adjust = "tukey")
pvals_df_20 <- as.data.frame(pairs_res_20)
pvals_df_20$contrast <- as.character(pvals_df_20$contrast)

pvals_df_20 <- pvals_df_20 %>%
    separate(contrast, into = c("comp1", "comp2"), sep = " - ")

pvals_df_20$Temperature <- as.factor(20)

#Temperature 22 - #No differences between week numbers and model fits well
censorsub <- subset(censor, censor$Species.x == "CM" & censor$Temperature == 22)
mod <- glm(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = censorsub)
plot(mod, main = "22C, diagnostic plots for CM")
summary(mod)
emm <- emmeans(mod, ~as.factor(WeekNum) | as.factor(Period))
pairs_res_22 <- pairs(emm, adjust = "tukey")
pvals_df_22 <- as.data.frame(pairs_res_22)
pvals_df_22$contrast <- as.character(pvals_df_22$contrast)

pvals_df_22 <- pvals_df_22 %>%
    separate(contrast, into = c("comp1", "comp2"), sep = " - ")

pvals_df_22$Temperature <- as.factor(22)

#Temperature 24 - #No differences between week numbers and model fits well
censorsub <- subset(censor, censor$Species.x == "CM" & censor$Temperature == 24)
mod <- glm(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = censorsub)
plot(mod, main = "24C, diagnostic plots for CM")
summary(mod)
emm <- emmeans(mod, ~as.factor(WeekNum) | as.factor(Period))
pairs_res_24 <- pairs(emm, adjust = "tukey")
pvals_df_24 <- as.data.frame(pairs_res_24)
pvals_df_24$contrast <- as.character(pvals_df_24$contrast)

pvals_df_24 <- pvals_df_24 %>%
    separate(contrast, into = c("comp1", "comp2"), sep = " - ")

pvals_df_24$Temperature <- as.factor(24)

#Temperature 26 - #No differences between week numbers and model fits well
censorsub <- subset(censor, censor$Species.x == "CM" & censor$Temperature == 26)
mod <- glm(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = censorsub)
plot(mod, main = "26C, diagnostic plots for CM")
summary(mod)
emm <- emmeans(mod, ~as.factor(WeekNum) | as.factor(Period))
pairs_res_26 <- pairs(emm, adjust = "tukey")
pvals_df_26 <- as.data.frame(pairs_res_26)
pvals_df_26$contrast <- as.character(pvals_df_26$contrast)

pvals_df_26 <- pvals_df_26 %>%
    separate(contrast, into = c("comp1", "comp2"), sep = " - ")

pvals_df_26$Temperature <- as.factor(26)

heat_df <- rbind(pvals_df_18, pvals_df_20, pvals_df_22, pvals_df_24, pvals_df_26)

#making a table for publish
library(kableExtra)
library(dplyr)

heat_df %>%
  select(comp1, comp2, estimate, SE, p.value, Temperature) %>%   # pick your columns
  kable(digits = 3,              # decimal places
        col.names = c("Comparison 1", "Comparison 2", "Difference", "Standard Error", "P value", "Temperature Treatment"),  # rename columns
        caption = "Differences between Proportion Eaten for each Week for Green Crabs")

#heat map
heat_df$signfi <- ifelse(heat_df$p.value < .05, "sig", "ns")

ggplot(heat_df, aes(x = comp1, y = comp2, fill = signfi)) + 
  geom_tile(color = "black", linewidth = 0.4) + 
  facet_grid(Period~Temperature,
  labeller = labeller(
    Period = c(
      "1" = "Period 1",
      "2" = "Period 2"
    ),
    Temperature = c(
      "18" = "18°C",
      "20" = "20°C",
      "22" = "22°C",
      "24" = "24°C",
      "26" = "26°C"
    ))) + 
  ggtitle("Differences between Week Number Within Periods for Green Crabs")+
  scale_fill_manual(
    name = "Significance",
    values = c("ns" = "darkorange", "sig" = "darkblue"),
    breaks = c("ns", "sig"),
    limits = c("ns", "sig"),
    drop = FALSE,
    guide = guide_legend(
      override.aes = list(
        fill = c("darkorange", "darkblue")
      )
    )
  )+
  xlab("Week Number")+
  ylab("Week Number")+
  scale_x_discrete(
  labels = c(
    "WeekNum1" = "1",
    "WeekNum2" = "2"
  ))+
  scale_y_discrete(
    labels = c(
      "WeekNum2" = "2",
      "WeekNum3" = "3"
    )
  )+
  theme(plot.title = element_text(size = 15, face = "bold", hjust = 0.5))


#For green crabs, there are no differences between week number within each Temperature treatment

```

Next up is Shore crabs. Shore crabs had a semi normal shape...? Some skew, so I'll try a GLM with normal distribution first and see how well the model does Again, I'll model the temperatures separately as I only care about differences within treatment. Same format as previous however, those with differences will contain pairwise differences

```{R echo=FALSE, warning=FALSE, message = FALSE, fig.width=7, fig.height=5}
#SHORE CRABS ------------------------------------------------------------------
par(mfrow=c(2,2))

#Temperature 18 - Ok fit... let's try a Gamma family
censorsub <- subset(censor, censor$Species.x == "HS" & censor$Temperature == 18)
mod1 <- glm(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = censorsub)
plot(mod1, main = "18C, Diagnostic plots for HS")
summary(mod1)

#model 2 and 3 failed! Leaving out for the document
#since 0's aren't allowed changing 0's to .001
#censorsub$proportion.eaten <- ifelse(censorsub$proportion.eaten <= 0, 0.001, censorsub$proportion.eaten)
#mod2 <- glm(proportion.eaten ~ as.factor(WeekNum), data = censorsub, family = Gamma(link = "inverse"))
#plot(mod2)
#summary(mod2)

#mod3 <- glm(proportion.eaten ~ as.factor(WeekNum), data = censorsub, family = Gamma(link = "identity"))
#plot(mod3)
#summary(mod3)
#AIC(mod1, mod2, mod3)

library(emmeans)
library(dplyr)
library(tidyr)
library(ggplot2)

#mod1 is best that says there are no differences between groups
emm <- emmeans(mod1, ~as.factor(WeekNum) | as.factor(Period))
pairs_res_18 <- pairs(emm, adjust = "tukey")
pvals_df_18 <- as.data.frame(pairs_res_18)
pvals_df_18$contrast <- as.character(pvals_df_18$contrast)

pvals_df_18 <- pvals_df_18 %>%
    separate(contrast, into = c("comp1", "comp2"), sep = " - ")

pvals_df_18$Temperature <- as.factor(18)


#mod1 is the best (normal model)
#after trying all of them, they all say the same thing - no differences between weeks

#Temperature 20 - Fit is OK, Week 2 and 3 are not different, but week 1 is different from week 2 and 3
censorsub <- subset(censor, censor$Species.x == "HS" & censor$Temperature == 20)
mod <- glm(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = censorsub)
plot(mod, main = "20C Diagnostic plots for HS")
summary(mod)

emm <- emmeans(mod, ~as.factor(WeekNum) | as.factor(Period))
pairs_res_20 <- pairs(emm, adjust = "tukey")
pvals_df_20 <- as.data.frame(pairs_res_20)
pvals_df_20$contrast <- as.character(pvals_df_20$contrast)

pvals_df_20 <- pvals_df_20 %>%
    separate(contrast, into = c("comp1", "comp2"), sep = " - ")

pvals_df_20$Temperature <- as.factor(20)

#Temperature 22 - Fit is good, only difference is between week 2 and 3 - CAUTION WHEN DOING FINAL ANAYSIS - MIGHT AFFECT USING WEEK 2 AND 3
censorsub <- subset(censor, censor$Species.x == "HS" & censor$Temperature == 22)
mod <- glm(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = censorsub)
par(mfrow = c(2,2))
plot(mod, main = "22C Diagnostic plots for HS")
summary(mod)

emm <- emmeans(mod, ~as.factor(WeekNum) | as.factor(Period))
pairs_res_22 <- pairs(emm, adjust = "tukey")
pvals_df_22 <- as.data.frame(pairs_res_22)
pvals_df_22$contrast <- as.character(pvals_df_22$contrast)

pvals_df_22 <- pvals_df_22 %>%
    separate(contrast, into = c("comp1", "comp2"), sep = " - ")

pvals_df_22$Temperature <- as.factor(22)

#Temperature 24 - Fit is good, one outlier that ate almost half of it's body weight
#no difference between week 1 and 2, but differences between 1-3 and 2-3
censorsub <- subset(censor, censor$Species.x == "HS" & censor$Temperature == 24)
mod <- glm(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = censorsub)
plot(mod, main = "24C Diagnostic plots for HS")
summary(mod)
emm <- emmeans(mod, ~as.factor(WeekNum) | as.factor(Period))
pairs_res_24 <- pairs(emm, adjust = "tukey")
pvals_df_24 <- as.data.frame(pairs_res_24)
pvals_df_24$contrast <- as.character(pvals_df_24$contrast)

pvals_df_24 <- pvals_df_24 %>%
    separate(contrast, into = c("comp1", "comp2"), sep = " - ")

pvals_df_24$Temperature <- as.factor(24)

#Temperature 26 - Fit is good, 3 outliers, no differences among groups. 
censorsub <- subset(censor, censor$Species.x == "HS" & censor$Temperature == 26)
mod <- glm(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = censorsub)
plot(mod, main = "26C Diagnostic plots for HS")
summary(mod)
emm <- emmeans(mod, ~as.factor(WeekNum) | as.factor(Period))
pairs_res_26 <- pairs(emm, adjust = "tukey")
pvals_df_26 <- as.data.frame(pairs_res_26)
pvals_df_26$contrast <- as.character(pvals_df_26$contrast)

pvals_df_26 <- pvals_df_26 %>%
    separate(contrast, into = c("comp1", "comp2"), sep = " - ")

pvals_df_26$Temperature <- as.factor(26)

heat_df <- rbind(pvals_df_18, pvals_df_20, pvals_df_22, pvals_df_24, pvals_df_26)

heat_df %>%
  select(comp1, comp2, estimate, SE, p.value, Temperature) %>%   # pick your columns
  kable(digits = 3,              # decimal places
        col.names = c("Comparison 1", "Comparison 2", "Difference", "Standard Error", "P value", "Temperature Treatment"),  # rename columns
        caption = "Differences between Proportion Eaten for each Week for Asian Shore Crabs")


heat_df$signfi <- ifelse(heat_df$p.value < .05, "sig", "ns")

ggplot(heat_df, aes(x = comp1, y = comp2, fill = signfi)) + 
  geom_tile(color = "black", linewidth = 0.4) + 
  facet_grid(Period~Temperature,
  labeller = labeller(
    Period = c(
      "1" = "Period 1",
      "2" = "Period 2"
    ),
    Temperature = c(
      "18" = "18°C",
      "20" = "20°C",
      "22" = "22°C",
      "24" = "24°C",
      "26" = "26°C"
    ))) + 
  ggtitle("Differences between Week Number Within Periods for Asian Shore Crabs")+
  scale_fill_manual(
    name = "Significance",
    values = c("ns" = "darkorange", "sig" = "darkblue"),
    breaks = c("ns", "sig"),
    limits = c("ns", "sig"),
    drop = FALSE,
    guide = guide_legend(
      override.aes = list(
        fill = c("darkorange", "darkblue")
      )
    )
  )+
  xlab("Week Number")+
  ylab("Week Number")+
  scale_x_discrete(
  labels = c(
    "WeekNum1" = "1",
    "WeekNum2" = "2"
  ))+
  scale_y_discrete(
    labels = c(
      "WeekNum2" = "2",
      "WeekNum3" = "3"
    )
  )+
  theme(plot.title = element_text(size = 15, face = "bold", hjust = 0.5))

#there are differences between weeks 2 and 3 for some temperature treatments
```

Same deal for rock crabs, I used simulated residuals from the DHARMa package as diagnostic plots since we're using zero-inflated models now.

```{R echo=FALSE, warning=FALSE, message = FALSE, fig.width=7, fig.height=5}
#CI-----------------------------------------------------------------------------

#Temperature 18 - worse fit, trying Gamma
censorsub <- subset(censor, censor$Species.x == "CI" & censor$Temperature == 18)
#mod1 <- glm(proportion.eaten ~ as.factor(WeekNum), data = censorsub)
#plot(mod1, main = "Temperature 18 Diagnostic plots for CI")
#since 0's aren't allowed changing 0's to .001
#censorsub$proportion.eaten <- ifelse(censorsub$proportion.eaten <= 0, 0.001, censorsub$proportion.eaten)
#mod2 <- glm(proportion.eaten ~ as.factor(WeekNum), data = censorsub, family = Gamma(link = "inverse"))
#plot(mod2)
#mod3 <- glm(proportion.eaten ~ as.factor(WeekNum), data = censorsub, family = Gamma(link = "logit"))
#plot(mod3)
#mod4 <- glm(proportion.eaten ~ as.factor(WeekNum), data = censorsub, family = Gamma(link = "log"))
#plot(mod4)

#AIC(mod1, mod2, mod3, mod4)

#the zero-inflated model is a good fit! no differences for zeros and continous values between the weeks
#ZIglm <- glmmTMB(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = censorsub, ziformula = ~as.factor(WeekNum), family = ziGamma((link= "inverse")))
#ZIglm.resids <- simulateResiduals(ZIglm)
#cat("18C Diagnostic plots for CI")
#plot(ZIglm.resids)
#summary(ZIglm)
#emm <- emmeans(ZIglm, ~ as.factor(WeekNum)*as.factor(Period), type = "response")
#pairs(emm)

mod <- glm(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = censorsub)
plot(mod)
summary(mod)

emm <- emmeans(mod, ~as.factor(WeekNum) | as.factor(Period))
pairs_res_18 <- pairs(emm, adjust = "tukey")
pvals_df_18 <- as.data.frame(pairs_res_18)
pvals_df_18$contrast <- as.character(pvals_df_18$contrast)

pvals_df_18 <- pvals_df_18 %>%
    separate(contrast, into = c("comp1", "comp2"), sep = " - ")

pvals_df_18$Temperature <- as.factor(18)

#Temperature 20 - better fit for normal data, when graphing out the response for CI at 20, it is normal except for the zero grouping
#There are differences between 1-2 and 1-3, but week 2-3 are the same
censorsub <- subset(censor, censor$Species.x == "CI" & censor$Temperature == 20)
#hist(censorsub$proportion.eaten)
#ZIglm <- glmmTMB(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = censorsub, ziformula = ~as.factor(WeekNum))
#ZIglm.resids <- simulateResiduals(ZIglm)
#cat("20C Diagnostic plots for CI")
#plot(ZIglm.resids)
#summary(ZIglm)
#emm <- emmeans(ZIglm, ~ as.factor(WeekNum)*as.factor(Period), type = "response")
#pairs(emm)
#no differences
mod <- glm(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = censorsub)
plot(mod)
summary(mod)
emm <- emmeans(mod, ~as.factor(WeekNum) | as.factor(Period))
pairs_res_20 <- pairs(emm, adjust = "tukey")
pvals_df_20 <- as.data.frame(pairs_res_20)
pvals_df_20$contrast <- as.character(pvals_df_20$contrast)

pvals_df_20 <- pvals_df_20 %>%
    separate(contrast, into = c("comp1", "comp2"), sep = " - ")

pvals_df_20$Temperature <- as.factor(20)


#Temperature 22 - good fit, no differences between any groups
censorsub <- subset(censor, censor$Species.x == "CI" & censor$Temperature == 22)
#ZIglm <- glmmTMB(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = censorsub, ziformula = ~as.factor(WeekNum), family = ziGamma((link= "inverse")))
#ZIglm.resids <- simulateResiduals(ZIglm)
#cat("22C Diagnostic plots for CI")
#plot(ZIglm.resids)
#summary(ZIglm)
#emm <- emmeans(ZIglm, ~ as.factor(WeekNum), type = "response")
#pairs(emm)

hist(censor$proportion.eaten)

mod <- glm(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = censorsub)
plot(mod)
summary(mod)
emm <- emmeans(mod, ~as.factor(WeekNum) | as.factor(Period))
pairs_res_22 <- pairs(emm, adjust = "tukey")
pvals_df_22 <- as.data.frame(pairs_res_22)
pvals_df_22$contrast <- as.character(pvals_df_22$contrast)

pvals_df_22 <- pvals_df_22 %>%
    separate(contrast, into = c("comp1", "comp2"), sep = " - ")

pvals_df_22$Temperature <- as.factor(22)


#Temperature 24 - good fit, no differences between week numbers
censorsub <- subset(censor, censor$Species.x == "CI" & censor$Temperature == 24)
#ZIglm <- glmmTMB(proportion.eaten ~ as.factor(WeekNum), data = censorsub, ziformula = ~as.factor(WeekNum), family = ziGamma((link= "inverse")))
#ZIglm.resids <- simulateResiduals(ZIglm)
#cat("24C Diagnostic plots for CI")
#plot(ZIglm.resids)
#summary(ZIglm)
#emm <- emmeans(ZIglm, ~ as.factor(WeekNum), type = "response")
#pairs(emm)

mod <- glm(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = censorsub)
plot(mod)
summary(mod)
emm <- emmeans(mod, ~as.factor(WeekNum) | as.factor(Period))
pairs_res_24 <- pairs(emm, adjust = "tukey")
pvals_df_24 <- as.data.frame(pairs_res_24)
pvals_df_24$contrast <- as.character(pvals_df_24$contrast)

pvals_df_24 <- pvals_df_24 %>%
    separate(contrast, into = c("comp1", "comp2"), sep = " - ")

pvals_df_24$Temperature <- as.factor(24)

#Temperature 26 - Good fit, no difference!
censorsub <- subset(censor, censor$Species.x == "CI" & censor$Temperature == 26)
hist(censorsub$proportion.eaten)
#ZIglm <- glmmTMB(proportion.eaten ~ as.factor(WeekNum) + as.factor(Period), data = censorsub, ziformula = ~1, family = ziGamma((link= "inverse")))
#ZIglm.resids <- simulateResiduals(ZIglm)
#cat("26C Diagnostic plots for CI")
#plot(ZIglm.resids)
#summary(ZIglm)
#emm <- emmeans(ZIglm, ~ as.factor(WeekNum), type = "response")
#pairs(emm)

mod <- glm(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = censorsub)
plot(mod)
summary(mod)
emm <- emmeans(mod, ~as.factor(WeekNum) | as.factor(Period))
pairs_res_26 <- pairs(emm, adjust = "tukey")
pvals_df_26 <- as.data.frame(pairs_res_26)
pvals_df_26$contrast <- as.character(pvals_df_26$contrast)

pvals_df_26 <- pvals_df_26 %>%
    separate(contrast, into = c("comp1", "comp2"), sep = " - ")

pvals_df_26$Temperature <- as.factor(26)

heat_df <- rbind(pvals_df_18, pvals_df_20, pvals_df_22, pvals_df_24, pvals_df_26)

heat_df %>%
  select(comp1, comp2, estimate, SE, p.value, Temperature) %>%   # pick your columns
  kable(digits = 3,              # decimal places
        col.names = c("Comparison 1", "Comparison 2", "Difference", "Standard Error", "P value", "Temperature Treatment"),  # rename columns
        caption = "Differences between Proportion Eaten for each Week for Rock Crabs")


heat_df$signfi <- ifelse(heat_df$p.value < .05, "sig", "ns")

ggplot(heat_df, aes(x = comp1, y = comp2, fill = signfi)) + 
  geom_tile(color = "black", linewidth = 0.4) + 
  facet_grid(Period~Temperature,
  labeller = labeller(
    Period = c(
      "1" = "Period 1",
      "2" = "Period 2"
    ),
    Temperature = c(
      "18" = "18°C",
      "20" = "20°C",
      "22" = "22°C",
      "24" = "24°C",
      "26" = "26°C"
    ))) + 
  ggtitle("Differences between Week Number Within Periods for Rock Crabs")+
  scale_fill_manual(
    name = "Significance",
    values = c("ns" = "darkorange", "sig" = "darkblue"),
    breaks = c("ns", "sig"),
    limits = c("ns", "sig"),
    drop = FALSE,
    guide = guide_legend(
      override.aes = list(
        fill = c("darkorange", "darkblue")
      )
    )
  )+
  xlab("Week Number")+
  ylab("Week Number")+
  scale_x_discrete(
  labels = c(
    "WeekNum1" = "1",
    "WeekNum2" = "2"
  ))+
  scale_y_discrete(
    labels = c(
      "WeekNum2" = "2",
      "WeekNum3" = "3"
    )
  )+
  theme(plot.title = element_text(size = 15, face = "bold", hjust = 0.5))

```

### Are there differences in consumption rate across different species and temperature? - Period Checking

#### Exploratory/Fitting the model

-I began by seeing if there were differences between periods for proportion consumed within each species and temperature treatments

-I fit different models for each species and temperature similar to what I did for finding acclimation effects. I only cared about within differences temperature treatment for a specific species which is why I did so.

-Period difference model \<- (Proportion consumed \~ Period, data = specific_species_and_temperature_treatment)

To understand if there were differences between periods, I first created a histogram graph of the distribution from the data to determine which model I should I use. I then created the model and tested the fit. If the model didn't fit well, I then used an alternative model and created a summary output. I began with rock crabs.

#### PERIOD DIFFERENCES RESULTS

-I found... (OLD RESULTS)

-   For CI, the only temperature treatment where there were differences between periods was temperature treatment 20

-   For CM, the only differences were in temperature treatment 24

-   For HS, temperature treatment 20, 24, 26 had differences in periods

-Since there were differences between periods for some temperature treatments I added it to my models (unless AIC ranking told me Periods made the model worse)

-The rest of the temperatures were not different between periods. Since there are differences between periods I will add it to the model

```{R, echo=FALSE,results='hide',fig.keep='all', fig.width=7, fig.height=5}
#I'm interested in understanding differences in proportion consumed across species and temperature. The period may also be a factor that affects proportion comsumed, so first I'll check if it does have an affect for proportion consumed.
#To check for differences across period, we'll check within trial and species

#CI--------------------------------------------------------------------------

#NOTE PREVIOUSLY TRIED TO USE ZERO-INFLATED MODELS TO ESTIMATE DIFFERENCES BETWEEN PERIODS
#however zeros only account for 7% of the total data, overkill, zero models kept failing. Replacing with normal GLMS

censorsub <- subset(censor, censor$Species.x == "CI" & censor$WeekNum == 3)
hist(censorsub$proportion.eaten)
par(mfrow=c(2,2))
mod <-glm(proportion.eaten ~ as.factor(Period)*as.factor(Temperature), data = censorsub)
plot(mod)
summary(mod)
emm <- emmeans(mod, ~as.factor(Period) | as.factor(Temperature))
pairs_res_CI <- pairs(emm, adjust = "tukey")
pvals_df_CI <- as.data.frame(pairs_res_CI)
pvals_df_CI$contrast <- as.character(pvals_df_CI$contrast)

pvals_df_CI <- pvals_df_CI %>%
    separate(contrast, into = c("comp1", "comp2"), sep = " - ")

pvals_df_CI$Species <- as.factor("CI")

#zeros only account for 7% of the total dataset, although it looks like 0's account for much more in the histogram, they aren't as strong as suspect which is why GLMs can be used.

```

Moving on to green crabs, which used normal GLMs

```{R, echo=FALSE,results='hide',fig.keep='all', fig.width=7, fig.height=5}

#model is good enough
censorsub <- subset(censor, censor$Species.x == "CM" & censor$WeekNum == 3)
#hist(censorsub$proportion.eaten)
par(mfrow=c(2,2))
mod <-glm(proportion.eaten ~ as.factor(Period)*as.factor(Temperature), data = censorsub)
plot(mod)
summary(mod)
emm <- emmeans(mod, ~as.factor(Period) | as.factor(Temperature))
pairs_res_CM <- pairs(emm, adjust = "tukey")
pvals_df_CM <- as.data.frame(pairs_res_CM)
pvals_df_CM$contrast <- as.character(pvals_df_CM$contrast)

pvals_df_CM <- pvals_df_CM %>%
    separate(contrast, into = c("comp1", "comp2"), sep = " - ")

pvals_df_CM$Species <- as.factor("CM")

```

Moving on to shore crabs, I used a zero inflated model for 18C and normal GLM for the rest of the models.

```{R, echo=FALSE,results='hide',fig.keep='all', fig.width=7, fig.height=5}
#HS----------------------------------------------------------------------------
censorsub <- subset(censor, censor$Species.x == "HS" & censor$WeekNum == 3)
#hist(censorsub$proportion.eaten)
par(mfrow=c(2,2))
mod <-glm(proportion.eaten ~ as.factor(Period)*as.factor(Temperature), data = censorsub)
plot(mod)
summary(mod)
emm <- emmeans(mod, ~as.factor(Period) | as.factor(Temperature))
pairs_res_HS <- pairs(emm, adjust = "tukey")
pvals_df_HS <- as.data.frame(pairs_res_HS)
pvals_df_HS$contrast <- as.character(pvals_df_HS$contrast)

pvals_df_HS <- pvals_df_HS %>%
    separate(contrast, into = c("comp1", "comp2"), sep = " - ")

pvals_df_HS$Species <- as.factor("HS")

```

```{R}
#COMBINGING ALL SPECIES FOR PERIOD DIFFERENCES TOGETHER

period_diff <- rbind(pvals_df_CI, pvals_df_CM, pvals_df_HS)

period_diff %>%
  select(comp1, comp2, estimate, SE, p.value, Temperature, Species) %>%   # pick your columns
  kable(digits = 3,              # decimal places
        col.names = c("Comparison 1", "Comparison 2", "Difference", "Standard Error", "P value", "Temperature Treatment", "Species"),  # rename columns
        caption = "Differences between Proportion Eaten Across Time Blocks")


period_diff$significant <- ifelse(period_diff$p.value <= 0.05, "sig", "ns")



ggplot(period_diff, aes(x = comp1, y = comp2, fill = significant)) + 
  geom_tile(color = "black", linewidth = 0.4) + 
  facet_grid(Species~Temperature,
  labeller = labeller(
    Species = c(
      "CI" = "Rock Crab",
      "CM" = "Green Crab",
      "HS" = "Asian Shore Crab"
    ),
    Temperature = c(
      "18" = "18°C",
      "20" = "20°C",
      "22" = "22°C",
      "24" = "24°C",
      "26" = "26°C"
    ))) + 
  ggtitle("Period 1 and 2 Differences for each Temperature \nand Species (Final Feeding Week)")+
  scale_fill_manual(
    name = "Significance",
    values = c("ns" = "darkorange", "sig" = "darkblue"),
    breaks = c("ns", "sig"),
    limits = c("ns", "sig"),
    drop = FALSE,
    guide = guide_legend(
      override.aes = list(
        fill = c("darkorange", "darkblue")
      )
    )
  )+
  xlab("Period Number")+
  ylab("Period Number")+
  scale_x_discrete(
  labels = c(
    "Period1" = "1"
  ))+
  scale_y_discrete(
    labels = c(
      "Period2" = "2"
    )
  )+
  theme(plot.title = element_text(size = 20, face = "bold", hjust = 0.5))
```

### Are there differences in consumption rate across different species and temperature? - Modeling the big question

#### Exploratory Graphs:

-I first graphed out what the proportion consumed across temperature looks like. Hopefully we find a model that supports what the graph suggests

-I also graphed out the proportion consumed for the whole dataset and for each species.

-When graphing the proportion consumed for the whole dataset it seems very skewed or even zero-inflated. However, what's interesting is that the distribution for the response variable changes depending on the species Each species has their own distribution type.

-I'll try to model the whole dataset first, but I will probably need to do model each species independently (unless there is a model that can handle multiple different distributions)

#### Modeling the data:

-The three explanatory variables I'm using are Period (factor), Temperature (numeric), and Species (for the whole dataset, factor)

-For each group, I began by making a full model and dredging it, then I use diagnostic plots to validate the model

-Since the Gamma family cannot work with zeros or negative numbers, for just the Gamma models, I converted all negative and zero values to .001.

-For zero-inflated gamma models, I converted them to just 0 instead of .001.

#### All Censor Model (censor model)

-I fit 4 types of models and dredged them to find the best ones.

-I fit a Zero-inflated Gamma (log, inverse, identity) Model and a GLM gamma model (also a gaussian model)

-I expected the Gamma or zero-inflated since the distribution seemed skewed; however, all models returned a poor fit -This was probably due to the different distributions among the species, so I moved to modeling each species separately.

#### Rock crab censor model

-I tried, zero inflated Gamma (inverse, log, identity) and GLM (identity, log, inverse) and no models returned a good fit

-I also added different combinations of variables (Temperature and Period and interactions); however, all models returned poor fits

-One model fit well; however, the summary output returned NaNs mostly. Unsure of how to handle this one.

#### Green crab censor model

-Dredged a full model and ran diagnostic plots on the best model.

-I found a good fit for the model that suggests a significantly small increase (.1% for every 1C) for proportion consumption in green crabs.

-Period was left out since it was not in a model ranked high enough in the AIC

#### Shore crab censor model

-Dredged a full model and ran diagnostic plots on the best model.

-I ran an AIC on the best models and different families; however, the fits were not the best.

-When I tried a different model that the AIC did not determine the best - the fit was great

-Further, when looking at the estimates for the temperature slope, I found that this model has a slight significant slope increase (.7% for every temperature unit increase) for proportion consumed.

-I'm likely to believe the best fitting model even though AIC didn't rank it the highest as it the diagnostic plots show evidence towards it being a good fitting model

-Also, all model summaries indicate this positive consumption increase as temperature increases.

### I then went back to model each species for the inclusive model (modeling inclusive now)

#### All DATA MODEL (inclusive model)

\- I tried 4 types of models and dredged to find no good models!

-The models I tried were, normal and Gamma GLMs along with normal and Gamma zero-inflated; however, none seemed to fit.

Rock crab inclusive model

-I fitted GLM models first and an okay fit; however, there were some concerns over the qqplot and scale-location plot indicate a wrong fit

-I then moved to zero-inflated models and found a model that fit well!

-The model summary suggests a decrease in decrease consumption as temperature increases AND it also suggests as temperature increases the amount of "0"s or those who aren't eating are also increasing as temperature increases

Green crabs (inclusive model)

-I fitted and dredged GLM models to the data

-I found a great model fit that included temperature and period (no interaction)

-There was no change in consumption across multiple temperatures; however, there was a slight increase in period 2 consumption compared to period 1 (significant)

Shore crabs (inclusive model)

-I fitted and dredged GLM models to the data

-I found two models that were great fits (3 outliers that seemed possible to throw out)

-Both models suggested a slight increase in consumption however one includes period and an interaction (between period and temperature).

-I'm leaning on throwing out the model that includes period since there is no significant change and therefore it's not important to include

#### Summary:

-I had to model each species and temperature treatment separately since they have different distributions (unless there's a model that can handle multiple different distributions). FOR censor model

-Rock crab data in the censor model was difficult to model and I couldn't find a good fitting model.

-Green and shore crabs had good fitting models; however, for shore crabs the model that fit the best was not ranked the best in the AIC (best ranking AIC models did not fit well) FOR inclusive model

-I found models that could fit each species, zero-inflated for rock crabs and GLMs for shore and green crabs

```{R, echo=FALSE,results='hide',fig.keep='all', fig.width=8, fig.height=6, warning = FALSE}
#In the model, I will include, Species and Temperature and use Period as a random effect
#Exploring the data first.

#only accounting for final week of trial
finalEatCensor <- subset(censor, censor$WeekNum == 3)

summary_df_censor <- finalEatCensor %>%
  group_by(Species.x, Temperature, Period) %>%
  summarise(
    mean = mean(proportion.eaten),
    se = sd(proportion.eaten) / sqrt(n())
  )

finalEatInclusive <- subset(inclusive, inclusive$WeekNum == 3)

summary_df_inclusive <- finalEatInclusive %>%
  group_by(Species.x, Temperature, Period) %>%
  summarise(
    mean = mean(proportion.eaten),
    se = sd(proportion.eaten) / sqrt(n())
  )

ggplot(summary_df_censor, aes(x = as.numeric(Temperature), y = mean, color = Species.x)) + geom_point(position = position_dodge(width = 0.3))+
  scale_color_manual(values = c("HS" = "darkred",
                                 "CM" = "darkgreen",
                                 "CI" = "darkorange"))+
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se),
                width = 0.1, size = 0.8, position = position_dodge(width = 0.3)) +
  geom_smooth(method = "loess", se = FALSE)+ scale_y_log10()+
  ylab("Logged Mean of Proportion Eaten")+
  xlab("Trial Temperature") + labs(color = "Species")+
  ggtitle("Proportion Consumed over Trial Temperature for the censor model")

ggplot(summary_df_inclusive, aes(x = as.numeric(Temperature), y = mean, color = Species.x)) + geom_point(position = position_dodge(width = 0.3))+
  scale_color_manual(values = c("HS" = "darkred",
                                 "CM" = "darkgreen",
                                 "CI" = "darkorange"))+
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se),
                width = 0.1, size = 0.8, position = position_dodge(width = 0.3)) +
  geom_smooth(method = "loess", se = FALSE)+ scale_y_log10()+
  ylab("Logged Mean of Proportion Eaten")+
  xlab("Trial Temperature") + labs(color = "Species")+
  ggtitle("Proportion Consumed over Trial Temperature for the inclusive model")



```

Little to no difference between censor and inclusive model. Start with censor model since it's safer

I'll begin with graphing proportions of the total dataset and then graphing distributions of each species.

```{R, echo=FALSE,results='hide',fig.keep='all', fig.width=7, fig.height=5, warning = FALSE}
#Graphing response variables to understand distributions-------------CENSOR-----

#proportion eaten is super skewed when graphed out. Let's take a look at each species...
hist(finalEatCensor$proportion.eaten, main = "Distribution of proportion eaten for the censor model")

censorsub <- subset(finalEatCensor, finalEatCensor$Species.x == "CI")
#zero-inflated
hist(censorsub$proportion.eaten, main = "Distribution of proportion eaten for the censor mode: rock crabs only")
censorsub <- subset(finalEatCensor, finalEatCensor$Species.x == "CM")
#normal
hist(censorsub$proportion.eaten, main = "Distribution of proportion eaten for the censor mode: green crabs only")
censorsub <- subset(finalEatCensor, finalEatCensor$Species.x == "HS")
#slight right skew
hist(censorsub$proportion.eaten, main = "Distribution of proportion eaten for the censor mode: shore crabs only")
#changing period to a factor
finalEatCensor$Period <- factor(finalEatCensor$Period)
#we can try graphing with Gamma family or even zero inflated to see if it'll work.
#we'll also dredge to get the best model.
```

I'll first model all the data in the censor model (all species). I'm trying zero-inflated models and normal GLMs with Gamma and Gaussian families.

```{R, echo=FALSE,fig.keep='all', fig.width=7, fig.height=5, warning = FALSE}
#GLM gamma and normal have poor fits
#dredge does not return any favorable models with temperature
#all.mod.glm.normal <- glm(proportion.eaten ~ Species.x*Temperature*Period, data = finalEatCensor, na.action = "na.fail")
#dredge(all.mod.glm.normal)

#best.mod.glm.normal <- glm(proportion.eaten ~ Species.x*Period, data = finalEatCensor, na.action = "na.fail")
#par(mfrow = c(2,2))
#plot(best.mod.glm.normal, main = "Normal GLM for all censor data")
#finalEatCensornozero <- finalEatCensor
#finalEatCensornozero$proportion.eaten <- ifelse(finalEatCensornozero$proportion.eaten <= 0, .001, finalEatCensornozero$proportion.eaten)
#all.mod.glm.normal <- glm(proportion.eaten ~ Species.x*Temperature*Period, data = finalEatCensornozero, family = Gamma(link = "log"), na.action = "na.fail")
#best.mod.glm.normal <- glm(proportion.eaten ~ Species.x*Temperature, data = finalEatCensor, na.action = "na.fail")
#plot(best.mod.glm.normal)
#all.mod.glm.normal <- glm(proportion.eaten ~ Species.x*Temperature*Period, data = finalEatCensornozero, family = Gamma(link = "inverse"), na.action = "na.fail")
#par(mfrow = c(2,2))
#plot(best.mod.glm.normal, main = "Gamma GLM for all censor data")
#best.mod.glm.normal <- glm(proportion.eaten ~ Species.x*Temperature, data = finalEatCensor, na.action = "na.fail")



#Trying zero-inflated gamma model
#all.ZIglm <- glmmTMB(proportion.eaten ~ Species.x*Temperature*Period, data = finalEatCensor, ziformula = ~1, family = ziGamma((link= "inverse")), na.action = "na.fail")
#dredge(all.ZIglm)
#best.mod <- all.ZIglm <- glmmTMB(proportion.eaten ~ Species.x*Temperature, data = finalEatCensor, ziformula = ~1, family = ziGamma((link= "inverse")), na.action = "na.fail")
#ZIglm.resids <- simulateResiduals(best.mod)
#cat("Zero-inflated Gamma for all censor data")
#plot(ZIglm.resids)

#all.ZIglm <- glmmTMB(proportion.eaten ~ Species.x*Temperature*Period, data = finalEatCensor, ziformula = ~Temperature, family = ziGamma((link= "inverse")), na.action = "na.fail")
#dredge(all.ZIglm)
#best.mod <- all.ZIglm <- glmmTMB(proportion.eaten ~ Species.x*Temperature, data = finalEatCensor, ziformula = ~Temperature, family = ziGamma((link= "inverse")), na.action = "na.fail")
#ZIglm.resids <- simulateResiduals(best.mod)
#plot(ZIglm.resids)
#trying zero-inflated normal model
#all.ZIglm <- glmmTMB(proportion.eaten ~ Species.x*Temperature*Period, data = finalEatCensor, ziformula = ~1, na.action = "na.fail")
#dredge(all.ZIglm)
#best.mod <- glmmTMB(proportion.eaten ~ Species.x*Temperature, data = finalEatCensor, ziformula = ~1, na.action = "na.fail")
#ZIglm.resids <- simulateResiduals(best.mod)
#cat("Zero-inflated normal for all censor data")
#plot(ZIglm.resids)

#here begins CHATGPT models (meeting with Brian)
finalEatCensor <- subset(censor, censor$WeekNum == 3) # | censor$WeekNum == 2
sum(finalEatCensor$proportion.eaten == 0)

finalEatCensor$binaryfed <- ifelse(finalEatCensor$amount.eaten > 0, 1, 0)
finalEatCensor$logmass <- log(finalEatCensor$WW)

finalEatCensor$log_mass_ws <- ave(
  finalEatCensor$logmass,
  finalEatCensor$Species.x,
  FUN = function(x) x - mean(x, na.rm = TRUE)
)

finalEatCensor$log_mass_bs <- ave(
  finalEatCensor$logmass,
  finalEatCensor$Species.x,
  FUN = function(x) mean(x, na.rm = TRUE)
)

finalEatCensor$runID <- paste(finalEatCensor$Temperature, finalEatCensor$Period, sep = "_")

library(glmmTMB)
dat <- subset(finalEatCensor, finalEatCensor$proportion.eaten == 0)

holddf <- finalEatCensor
holddf$proportion.eaten <- ifelse(holddf$proportion.eaten == 0, .001, holddf$proportion.eaten)

data = subset(finalEatCensor, proportion.eaten > 0)
data$temp_squared <- data$Temperature^2

ggplot(aes(x = as.factor(Temperature), y = (proportion.eaten), fill = Species.x), data = data) + 
  geom_boxplot() + 
  facet_wrap(~Species.x, labeller = 
               labeller(Species.x = c("CI" = "Rock Crab", "CM" = "Green Crab", "HS" = "Asian Shore Crab"))) + 
  scale_fill_manual(name = "Species", values = c("CI" = "darkorange", "CM" = "darkgreen", "HS" = "darkred"),
                    labels = c("CI" = "Rock Crab", "CM" = "Green Crab", "HS" = "Asian Shore Crab"))+
  theme_classic() +
  theme(plot.title = element_text(size = 15, face = "bold", hjust = 0))+
  xlab("Temperature (°C)")+
  ylab("Log Proportion Eaten (% of Body Weight)") +
  ggtitle("Proportion Eaten (% Body Weight) for each Temperature Treatment")


ggplot(finalEatCensor, aes(x = as.factor(Temperature), fill = as.factor(binaryfed))) +
  geom_bar(position = "fill") + 
  facet_wrap(~Species.x, labeller = 
               labeller(Species.x = c("CI" = "Rock Crab", "CM" = "Green Crab", "HS" = "Asian Shore Crab"))) + 
  scale_fill_manual(name = "Eaten (Y/N)", values = c("0" = "darkred", "1" = "darkgreen"),
                    labels = c("0" = "No", "1" = "Yes"))+
  theme_classic() +
  theme(plot.title = element_text(size = 15, face = "bold", hjust = 0))+
  xlab("Temperature (°C)")+
  ylab("Percentage (%)") +
  ggtitle("Percentage of Whether the Crab Ate or Not")

data2 <- subset(data, data$Species.x == "CI")

ggplot(aes(x = as.factor(Temperature), y = (proportion.eaten)), data = data2) + 
  geom_boxplot() +
  theme_classic() +
  theme(plot.title = element_text(size = 15, face = "bold", hjust = 0))+
  xlab("Temperature (°C)")+
  ylab("Proportion Eaten") +
  ggtitle("Proportion Eaten for each Temperature Treatment")

ggplot(aes(x = as.factor(Temperature), y = amount.eaten, fill = Species.x), data = data) + geom_boxplot() + theme_classic()

ggplot(aes(x = WW, y = amount.eaten, color = Species.x), data = data) +
  geom_point() +
  geom_smooth(method = "loess", span = 1) +
  facet_wrap(~Species.x, scales = "free")

food.mod1 <- glmmTMB(amount.eaten ~ WW*as.factor(Period) + Species.x + (1 | ID), family = Gamma(link = "identity"), data = data, na.action = "na.fail")
#dredge(food.mod1)


#AIC(food.mod1, food.mod2, food.mod3, food.mod4, food.mod5, food.mod6)

#summary(food.mod1)
#sim_res_food <- simulateResiduals(fittedModel = food.mod1, n = 1000)
#plot(sim_res_food)

ggplot(finalEatCensor, aes(x = as.factor(Temperature), y = log(amount.eaten), color = Species.x)) +
  geom_boxplot() +
  ylab("Amount Eaten (g)")+
  ggtitle("Amount Eaten by Rock Crabs over Temperature")+
  theme(legend.position = "none") +
  facet_wrap(~Species.x)

```

Using Firth for Eat or Do Not Eat Modeling
```{R}
#using 
finalEatCensorold <- finalEatCensor

library(dplyr)

#creating a test zero point for the censor model
#finalEatCensor <- finalEatCensor %>%
#  add_row(
#    Species.x = "CM",
#    Temperature = 18,
#    binaryfed = 0,
#    Period = 1,
#    runID = "22_1"
#  )

finalEatCensor <- subset(finalEatCensor, finalEatCensor$Species.x != "CM")

all.mod <- brglm(binaryfed ~ Species.x*Temperature*as.factor(Period), family = binomial, data = finalEatCensor, na.action = "na.fail")
dredge(all.mod, rank = "AICc")

#model is better without period, additionally there is an interaction between species and temperature

best.mod <- brglm(binaryfed ~ Species.x*Temperature, family = binomial, data = finalEatCensor, na.action = "na.fail")
summary(best.mod)

#what's the best way to create diagnostic plots for this?

newdat <- NULL

finalEatCensor$Species.x <- factor(finalEatCensor$Species.x)
newdat <- expand.grid(Temperature = seq(min(finalEatCensor$Temperature), max(finalEatCensor$Temperature), length.out = 100), Species.x = levels(finalEatCensor$Species.x))
newdat$Species.x <- factor(newdat$Species.x, levels = levels(finalEatCensor$Species.x))
newdat$pred <- predict(best.mod, newdata = newdat, type = "response")

preds <- predict(best.mod, newdata = newdat, type = "response", se.fit = TRUE)
newdat$pred  <- preds$fit
newdat$lower <- pmax(preds$fit - 1.96 * preds$se.fit, 0)
newdat$upper <- pmin(preds$fit + 1.96 * preds$se.fit, 1)  # cap at 1 for probability

ggplot(finalEatCensor, aes(x = Temperature, y = binaryfed, color = Species.x)) +
  geom_point(position = position_jitter(width = .45, height = 0.05), alpha = 0.6) +
  geom_line(data = newdat, aes(x = Temperature, y = pred, color = Species.x), linewidth = 1) +
  geom_ribbon(data = newdat, aes(x = Temperature, ymin = lower, ymax = upper, fill = Species.x),
            alpha = 0.2, color = NA, inherit.aes = FALSE) +
  scale_y_continuous(breaks = c(0, 1), labels = c("Didn't Eat", "Did Eat"))+ 
  scale_x_continuous(breaks = c(18, 20, 22, 24, 26))+
  ggtitle("Predicted Eat or Didn't Eat") + 
  scale_fill_manual(name = "Species",
                  values = c("CM" = "darkgreen", "HS" = "darkred", "CI" = "darkorange"),
                  breaks = c("HS", "CM", "CI"),
                  labels = c("Asian Shore Crab", "Green Crab", "Rock Crab"))+
  scale_color_manual(name = "Species",
                     values = c("CM" = "darkgreen",
                                "HS" = "darkred",
                                "CI" = "darkorange"),
                     breaks = c("HS", "CM", "CI"),
                     labels = c("Asian Shore Crab", "Green Crab", "Rock Crab"))+
  xlab("Temperature (°C)")+
  ylab("")+
  ggtitle("")+theme_classic()

finalEatCensor <- finalEatCensorold

#-----------------------------------

#model fails due to compelte separation
all.zero <- glmmTMB(binaryfed ~ Species.x*Temperature*as.factor(Period) + 
                        (1 | runID), family = binomial, data = finalEatCensor, na.action = "na.fail")
dredge(all.zero, rank = "AICc")


#same issue with no 0 values in green crabs
#summary(zero_model)
# Simulate DHARMa residuals
#sim_res_zero <- simulateResiduals(fittedModel = zero_model, n = 1000)
# Basic diagnostic plots
#plot(sim_res_zero)                  # uniformity, QQ, residuals vs predicted
#plot(sim_res_zero, type = "predicted") # residuals vs fitted values
# Test for over/underdispersion and zero-inflation
#testDispersion(sim_res_zero)
#testZeroInflation(sim_res_zero)  # should be low for positive model

#binary data
library(dplyr)

temp_seq <- seq(
  min(finalEatCensor$Temperature, na.rm = TRUE),
  max(finalEatCensor$Temperature, na.rm = TRUE),
  length.out = 100
)

pred_df <- expand.grid(
  Temperature = temp_seq,
  Species.x = c("CI", "CM", "HS"),
  Period = unique(finalEatCensor$Period)[2]  # pick any level
)

pred_link <- predict(
  zero_model,
  newdata = pred_df,
  type = "link",
  se.fit = TRUE,
  re.form = NA
)

pred_df <- pred_df |>
  dplyr::mutate(
    fit_link = pred_link$fit,
    se_link  = pred_link$se.fit,
    prob     = plogis(fit_link),
    lower    = plogis(fit_link - se_link),
    upper    = plogis(fit_link + se_link)
  )

pred_df$Species.x <- factor(pred_df$Species.x, levels = c("HS", "CM", "CI"))
finalEatCensor$Species.x <- factor(finalEatCensor$Species.x, levels = c("HS", "CM", "CI"))

ggplot(pred_df, aes(x = Temperature, y = prob, color = Species.x)) +
  geom_point(data = finalEatCensor, aes(x = Temperature, y = binaryfed, color = Species.x),
             position = position_jitter(height = 0.1, width = 0.25),
             alpha = 0.5, inherit.aes = FALSE) +
  geom_ribbon(
    aes(ymin = lower, ymax = upper, fill = Species.x),
    alpha = 0.25,
    color = NA
  ) +
  geom_line(linewidth = 1.2) +
  theme_classic() +
  labs(
    x = "Temperature (°C)",
    y = "Percentage (%)",
    color = "Species"
  ) +
  scale_color_manual(
    values = c("CI" = "darkorange", "CM" = "darkgreen", "HS" = "darkred"),
    labels = c("CI" = "Rock Crab", "CM" = "Green Crab", "HS" = "Asian Shore Crab")
  ) +
  scale_fill_manual(
    values = c("CI" = "darkorange", "CM" = "darkgreen", "HS" = "darkred")
  ) +
  guides(fill = "none") +
  ggtitle("Predicted Probability of a Crab Eating at Temperature") +
  theme(plot.title = element_text(size = 15, face = "bold", hjust = 0.5))

ggplot(data, aes(x = log(WW), y = amount.eaten, color = Species.x))+geom_point()+geom_smooth(method="loess")

ggplot(data, aes(x = as.factor(Temperature), y = amount.eaten, fill = Species.x)) + geom_boxplot()

```
Positive Model GAM

```{R}
data$Temperature <- as.numeric(data$Temperature)
data$ID <- as.factor(data$ID)
data$Species.x <- as.factor(data$Species.x)

data_pos <- subset(data, data$amount.eaten > 0)

data$amount.eaten.log <- log(data$amount.eaten)

gam_model <- gam(amount.eaten ~ s(Temperature, by = Species.x, bs = "tp", k = 5)
                 + log_mass_ws
                 + Species.x
                 + s(ID, bs = "re"),
  data = data,
  family = Gamma(link = "inverse"),
  method = "REML",
  na.action = "na.fail"
)

data$log_eaten_ws <- ave(
  data$amount.eaten.log,
  data$Species.x,
  FUN = function(x) x - mean(x, na.rm = TRUE)
)

gam_model <- gam(log_eaten_ws ~ s(Temperature, by = Species.x, bs = "tp", k = 5)
                 + log_mass_ws,
  data = data,
  family = gaussian(link = "inverse"),
  method = "REML",
  na.action = "na.fail"
)


par(mfrow = c(2,2))
gam.check(gam_model)

#GAMs punish for being "too" wiggly
dredge(gam_model, rank = "AICc")

summary(gam_model)

#The next section covers smooth terms. For smooths coefficients are not printed. 
#This is because each smooth has several coefficients - one for each basis function. 
#Instead, the first column reads edf, which stands for effective degrees of freedom. 
#This value represents the complexity of the smooth. An edf of 1 is equivalent to a 
#straight line. An edf of 2 is equivalent to a quadratic curve, and so on, with higher 
#edfs describing more wiggly curves.

#A good way to interpret significance for smooth terms in GAMs is this: 
#a significant smooth term is one where you can not draw a horizontal line 
#through the 95% confidence interval.
plots <- draw(gam_model, residuals = TRUE, ci_level = 0.95, rug = TRUE)
for(i in 1:7){
  print(plots[[i]])
}


sim_res_GAM <- simulateResiduals(fittedModel = gam_model, n = 1000)
plot(sim_res_GAM)
testDispersion(sim_res_GAM)

#you could get a GAM model that preforms ok on DHARMa diagnostics and fails some gam.check values
#OR
#you could get a GAM model that preforms poorly on DHARMa diagnostics, but passes it's gam.check values

#between adding smoother/interaction for weight and species
#what do the relationships look like?
#dredge supports the GAM model with good DHARMa diagnostics

# Build prediction grid
pred_grid <- expand.grid(
  Temperature  = seq(min(data$Temperature), max(data$Temperature), length.out = 200),
  Species.x    = unique(data$Species.x),
  log_mass_ws  = mean(data$log_mass_ws, na.rm = TRUE),
  ID           = data$ID[1]  # Dummy ID; excluded via exclude below
)

# Predict on response scale, population-level (no random effects)
preds <- predict(
  gam_model,
  newdata  = pred_grid,
  type     = "response",
  exclude  = "s(ID)",
  se.fit   = TRUE
)

pred_grid$fit    <- preds$fit
pred_grid$se     <- preds$se.fit
pred_grid$lower  <- pred_grid$fit - 1.96 * pred_grid$se
pred_grid$upper  <- pred_grid$fit + 1.96 * pred_grid$se

# Plot
ggplot() +
  geom_point(
    data = data,
    aes(x = Temperature, y = amount.eaten, color = Species.x),
    alpha    = 0.4,
    size     = 1.5,
    position = position_jitter(width = 0.2, height = 0)
  ) +
  geom_ribbon(
    data = pred_grid,
    aes(x = Temperature, ymin = lower, ymax = upper, fill = Species.x),
    alpha = 0.2
  ) +
  geom_line(
    data = pred_grid,
    aes(x = Temperature, y = fit, color = Species.x),
    linewidth = 1.2
  ) +
  scale_color_manual(
    name   = "Species",
    values = c("CI" = "darkorange", "CM" = "darkgreen", "HS" = "darkred"),
    labels = c("CI" = "Cancer irroratus", "CM" = "Carcinus meanus", "HS" = "Hemigrapsus sanguineus")
  ) +
  scale_fill_manual(
    name   = "Species",
    values = c("CI" = "darkorange", "CM" = "darkgreen", "HS" = "darkred"),
    labels = c("CI" = "Cancer irroratus", "CM" = "Carcinus meanus", "HS" = "Hemigrapsus sanguineus")
  ) +
  scale_x_continuous(breaks = c(18, 20, 22, 24, 26)) +
  labs(
    x     = "Temperature (°C)",
    y     = "Amount Eaten",
    title = "GAM Predicted Amount Eaten by Temperature and Species"
  ) +
  theme_classic() +
  theme(
    legend.position = "right",
    plot.title      = element_text(hjust = 0.5)
  )
```


Positive Model Typical
```{R}
#model creations
#Amount Eaten with log_mass_bs -------------------------------------------------------------------- OK MODEL - potential winner
library(DHARMa)

#the code above creates a temperature squared value for CI and not CM or HS (gives them a fat 0)
#when the model calculates the number, CM and HS are seen as not to have a quadratic term

#log_mass_ws_sc -> larger individuals will eat more (theory) therefore accounting for size is important if using amount eaten.
#we log the mass because this is a truer representation to what we see in nature (a crab twice as heavy doesn't eat twice as much, the relationship is more logged)
#removing log_mass_ws_sc only yields signfiicant results/differences at 24C, "At 24°C specifically, larger crabs are eating meaningfully more than smaller crabs, and without mass in the model that variation gets dumped into the residuals."

#log_mass_ws_sc squared -> relationship between mass and consumption isn't linear, larger crabs consumption is more, but not directly linear to size.

#1 / ID accounts for individual variance among crabs

#dispformula -> each species has it's own variance (distance from the mean)

# Center temperature before squaring
mean_temp <- mean(data$Temperature)

#squaring only rock crba values
data$temp_sq_CI <- ifelse(data$Species.x == "CI", 
                          (data$Temperature - mean_temp)^2, 0)

#log
finalEatCensor$logmass <- log(finalEatCensor$WW)

#Centering
finalEatCensor$log_mass_ws <- ave(
  finalEatCensor$logmass,
  finalEatCensor$Species.x,
  FUN = function(x) x - mean(x, na.rm = TRUE)
)

#scaling
data$log_mass_ws_sc <- scale(data$log_mass_ws)
data$log_mass_ws_sc2 <- data$log_mass_ws_sc^2

data$log_mass_ws_sq <- data$log_mass_ws^2

data$temp_sq <- (data$Temperature - mean_temp)^2

best.mod2 <- glmmTMB(
  amount.eaten ~ Species.x * Temperature + temp_sq_CI + 
                log_mass_ws_sq*Species.x + (1 | ID),
  family = gaussian(link = "log"),
  dispformula = ~ Species.x,
  data = data,
  na.action = "na.fail"
)

AIC(best.mod1, best.mod2)

#runID varaince is essentially zero "runID    (Intercept) 1.613e-10 1.27e-05"
#ID is meaningful (more)

summary(best.mod2)
sim_res <- simulateResiduals(fittedModel = best.mod2, n = 1000)
plot(sim_res)
testUniformity(sim_res)
testDispersion(sim_res)
plotResiduals(sim_res, data$Temperature)
plotResiduals(sim_res, data$Species.x)
plotResiduals(sim_res, data$log_mass_ws_sc)
diagnose(best.mod1)
```

Graphing the prediction
```{R}
# ── EXACT-TEMPERATURE CONTRASTS ──────────────────────────────────────────────

pred_exact <- expand.grid(
  Temperature = c(18, 20, 22, 24, 26),
  Species.x   = c("CI", "CM", "HS")
) %>%
  mutate(
    temp_sq_CI     = ifelse(Species.x == "CI", (Temperature - mean_temp)^2, 0),
    log_mass_ws    = 0,
    log_mass_ws_sq = 0,
    ID             = NA
  )

# Predictions on link scale
pred_exact$fit_link <- predict(best.mod1, newdata = pred_exact,
                               re.form = NA, allow.new.levels = TRUE)

# Model matrix must match formula exactly — no Period, unscaled mass terms
mm_exact <- model.matrix(
  ~ Species.x * Temperature + temp_sq_CI + log_mass_ws + log_mass_ws_sq,
  data = pred_exact
)

vc <- vcov(best.mod1)$cond
pred_exact$se_link <- sqrt(diag(mm_exact %*% vc %*% t(mm_exact)))
pred_exact$fit     <- exp(pred_exact$fit_link)

pred_exact %>% select(Temperature, Species.x, fit, se_link)

# Pairwise contrasts on link scale with Bonferroni correction (3 pairs × 5 temps = 15)
contrast_df <- pred_exact %>%
  group_by(Temperature) %>%
  summarise(
    CI_CM_diff  = fit_link[Species.x == "CI"] - fit_link[Species.x == "CM"],
    CI_CM_se    = sqrt(se_link[Species.x == "CI"]^2 + se_link[Species.x == "CM"]^2),
    CI_CM_z     = CI_CM_diff / CI_CM_se,
    CI_CM_p     = 2 * pnorm(-abs(CI_CM_z)),

    CI_HS_diff  = fit_link[Species.x == "CI"] - fit_link[Species.x == "HS"],
    CI_HS_se    = sqrt(se_link[Species.x == "CI"]^2 + se_link[Species.x == "HS"]^2),
    CI_HS_z     = CI_HS_diff / CI_HS_se,
    CI_HS_p     = 2 * pnorm(-abs(CI_HS_z)),

    CM_HS_diff  = fit_link[Species.x == "CM"] - fit_link[Species.x == "HS"],
    CM_HS_se    = sqrt(se_link[Species.x == "CM"]^2 + se_link[Species.x == "HS"]^2),
    CM_HS_z     = CM_HS_diff / CM_HS_se,
    CM_HS_p     = 2 * pnorm(-abs(CM_HS_z))
  ) %>%
  mutate(
    CI_CM_p_adj = pmin(CI_CM_p * 15, 1),
    CI_HS_p_adj = pmin(CI_HS_p * 15, 1),
    CM_HS_p_adj = pmin(CM_HS_p * 15, 1)
  )

contrast_df %>%
  mutate(
    CI_CM_ratio = exp(CI_CM_diff),
    CI_HS_ratio = exp(CI_HS_diff),
    CM_HS_ratio = exp(CM_HS_diff)
  ) %>%
  select(Temperature,
         CI_CM_ratio, CI_CM_p_adj,
         CI_HS_ratio, CI_HS_p_adj,
         CM_HS_ratio, CM_HS_p_adj)


# ── PREDICTION CURVE FOR PLOTTING ────────────────────────────────────────────

temp_seq <- seq(18, 26, length.out = 100)

pred_df <- expand.grid(
  Temperature = temp_seq,
  Species.x   = c("CI", "CM", "HS")
) %>%
  mutate(
    temp_sq_CI     = ifelse(Species.x == "CI", (Temperature - mean_temp)^2, 0),
    log_mass_ws    = 0,
    log_mass_ws_sq = 0,
    ID             = NA
  )

pred_df$fit_link <- predict(best.mod1, newdata = pred_df,
                            re.form = NA, allow.new.levels = TRUE)

# Again: match formula exactly
mm <- model.matrix(
  ~ Species.x * Temperature + temp_sq_CI + log_mass_ws + log_mass_ws_sq,
  data = pred_df
)

vc <- vcov(best.mod1)$cond
pred_df$se_link <- sqrt(diag(mm %*% vc %*% t(mm)))

pred_df <- pred_df %>%
  mutate(
    fit = exp(fit_link),
    lwr = exp(fit_link - 1.96 * se_link),
    upr = exp(fit_link + 1.96 * se_link)
  )

pred_df %>%
  filter(Species.x == "CI") %>%
  select(Temperature, fit, lwr, upr, se_link)


# ── PLOT ──────────────────────────────────────────────────────────────────────

ggplot() +
  geom_point(data = data,
             aes(x = Temperature, y = amount.eaten, color = Species.x),
             position = position_jitter(width = 0.2), alpha = 0.4) +
  geom_ribbon(data = pred_df,
              aes(x = Temperature, ymin = lwr, ymax = upr, fill = Species.x),
              alpha = 0.2, color = NA) +
  geom_line(data = pred_df,
            aes(x = Temperature, y = fit, color = Species.x),
            linewidth = 1.2) +
  scale_color_manual(
    limits = c("HS", "CM", "CI"),
    values = c("CI" = "darkorange", "CM" = "darkgreen", "HS" = "darkred"),
    labels = c("CI" = "Rock Crab", "CM" = "Green Crab", "HS" = "Asian Shore Crab"),
    name = "Species"
  ) +
  scale_fill_manual(
    limits = c("HS", "CM", "CI"),
    values = c("CI" = "darkorange", "CM" = "darkgreen", "HS" = "darkred"),
    guide = "none"
  ) +
  scale_y_log10(labels = scales::label_number(accuracy = 0.01)) +
  scale_x_continuous(breaks = c(18, 20, 22, 24, 26)) +
  xlab("Temperature (°C)") +
  ylab("Log10 Amount Eaten (g)") +
  ggtitle("Predicted Amount Eaten Across Temperature") +
  theme_classic() +
  theme(plot.title = element_text(size = 15, face = "bold", hjust = 0.5))
```

The normal GLM fit the best; however, it ranked lower on the AIC. There were other higher ranking models according to the AIC but the diagnostic plots proved problematic. Models okay, let's compare these to the inclusive model and see how they fit over that data.

### THIS IS NOW SWITCHING TO THE INCLUSIVE MODEL GRAPHS

I'll begin with modeling all the data as a whole same way I started with my censor data. I'll try GLMs and then zero inflated models.

```{R, echo=FALSE,fig.keep='all', fig.width=7, fig.height=5, warning = FALSE}
#finaleatinclusive
#hist(finalEatInclusive$proportion.eaten, main = "Distribution of the proportion eaten: Inclusive Model")

#mod <- glm(proportion.eaten ~ Species.x*Period*Temperature, data = finalEatInclusive, na.action = "na.fail")
#dredge(mod)

#mod1 <- glm(proportion.eaten ~ Temperature*Species.x, data = finalEatInclusive)
#par(mfrow = c(2,2))
#plot(mod1, main = "All inclusive model data: normal GLM")
#mod2 <- glm(proportion.eaten ~ Temperature*Species.x*Period, data = finalEatInclusive)
#par(mfrow = c(2,2))
#plot(mod2)
#mod3 <- glm(proportion.eaten ~ Temperature*Species.x + Period, data = finalEatInclusive)
#par(mfrow = c(2,2))
#plot(mod3)

#finalEatInclusivenozero <- finalEatInclusive
#finalEatInclusivenozero$proportion.eaten <- ifelse(finalEatInclusive$proportion.eaten <= 0, .001, finalEatInclusive$proportion.eaten)
#mod1 <- glm(proportion.eaten ~ Temperature*Species.x, family = Gamma(link = "inverse"), data = finalEatInclusivenozero)
#par(mfrow = c(2,2))
#plot(mod1, main = "All inclusive model data: Gamma")
#cat("Summary output for the best GLM Gamma Inclusive model")
#summary(mod1)
#mod2 <- glm(proportion.eaten ~ Temperature*Species.x*Period, family = Gamma(link = "inverse"), data = finalEatInclusivenozero)
#par(mfrow = c(2,2))
#plot(mod2)
#mod3 <- glm(proportion.eaten ~ Temperature*Species.x + Period, family = Gamma(link = "inverse"), data = finalEatInclusivenozero)
#par(mfrow = c(2,2))
#plot(mod3)

#mod1 <- glm(proportion.eaten ~ Temperature*Species.x, family = Gamma(link = "log"), data = finalEatInclusivenozero)
#par(mfrow = c(2,2))
#plot(mod1)
#mod2 <- glm(proportion.eaten ~ Temperature*Species.x*Period, family = Gamma(link = "log"), data = finalEatInclusivenozero)
#par(mfrow = c(2,2))
#plot(mod2)
#mod3 <- glm(proportion.eaten ~ Temperature*Species.x + Period, family = Gamma(link = "log"), data = finalEatInclusivenozero)
#par(mfrow = c(2,2))
#plot(mod3)

#all.ZIglm <- glmmTMB(proportion.eaten ~ Species.x*Temperature*Period, data =finalEatInclusive, ziformula = ~Temperature, na.action = "na.fail")
#dredge(all.ZIglm)

#finalEatInclusivenozero <- finalEatInclusive
#finalEatInclusivenozero$proportion.eaten <- ifelse(finalEatInclusive$proportion.eaten < 0, 0, finalEatInclusive$proportion.eaten)

#best.mod <- glmmTMB(proportion.eaten ~ Species.x*Temperature*Period, data = finalEatInclusivenozero, ziformula = ~Temperature, family = ziGamma(link = "inverse"), na.action = "na.fail")
#ZIglm.resids <- simulateResiduals(best.mod)
#cat("All inclusive model data: Zero-Inflation")
#plot(ZIglm.resids)

#here begins CHATGPT models (meeting with Brian)
sum(finalEatInclusive$proportion.eaten == 0)

finalEatInclusive$binaryfed <- ifelse(finalEatInclusive$amount.eaten > 0, 1, 0)
finalEatInclusive$logmass <- log(finalEatInclusive$WW)
finalEatInclusive$log_mass_ws <- ave(
  finalEatInclusive$logmass,
  finalEatInclusive$Species.x,
  FUN = function(x) x - mean(x, na.rm = TRUE)
)

finalEatInclusive$log_mass_bs <- ave(
  finalEatInclusive$logmass,
  finalEatInclusive$Species.x,
  FUN = function(x) mean(x, na.rm = TRUE)
)

finalEatInclusive$runID <- paste(finalEatInclusive$Temperature, finalEatInclusive$Period, sep = "_")
library(glmmTMB)
# Hurdle model: zeros vs positives (binomial) + positive consumption (Gamma)
pos_model <- glmmTMB(
  proportion.eaten ~ log_mass_ws*Species.x*Temperature +
                (1 | ID) + (1 | runID),
  family = Gamma(link = "log"),
  data = subset(finalEatInclusive, proportion.eaten > 0)
)

# Simulate DHARMa residuals
sim_res_pos <- simulateResiduals(fittedModel = pos_model, n = 1000)

# Basic diagnostic plots
plot(sim_res_pos)                  # uniformity, QQ, residuals vs predicted
plot(sim_res_pos, type = "predicted") # residuals vs fitted values

# Test for over/underdispersion and zero-inflation
testDispersion(sim_res_pos)
testZeroInflation(sim_res_pos)  # should be low for positive model


zero_model <- glmmTMB(
  binaryfed ~ log_mass_ws + Species.x + Temperature +
                  (1 | ID) + (1 | runID),
  family = binomial,
  data = finalEatInclusive
)

# Simulate DHARMa residuals
sim_res_zero <- simulateResiduals(fittedModel = zero_model, n = 1000)

# Basic diagnostic plots
plot(sim_res_zero)                  # uniformity, QQ, residuals vs predicted
plot(sim_res_zero, type = "predicted") # residuals vs fitted values

# Test for over/underdispersion and zero-inflation
testDispersion(sim_res_zero)
testZeroInflation(sim_res_zero)  # should be low for positive model

summary(pos_model)
summary(zero_model)

```

EXTRAS

#### Amount of who did not eat by species and trial

```{R, echo = FALSE, warning = FALSE}
all$eaten <- factor(all$eaten, levels = c("YES", "NO"))
all$Species.x <- factor(all$Species.x, levels = c("HS", "CM", "CI"))
ggplot(all, aes(x = Temperature, fill = eaten)) + geom_bar(stat = "count") + facet_wrap(~Species.x)+
  scale_fill_manual(values = c("YES" = "darkolivegreen4",
                                "NO"="darkred"))+ggtitle("Amount of Times Individuals did not eat")+xlab("Trial Temperature") + ylab("Count")

#Amount of those who are still eating vs not eating
all$still_eating <- factor(all$still_eating, leve = c("NO", "YES"))
ggplot(all, aes(x = Temperature, fill = still_eating))+ geom_bar(stat = "count") + facet_wrap(~Species.x)+
  ggtitle("Amount of those who are still eating vs not eating") +
  scale_fill_manual(values = c("YES" = "darkolivegreen4",
                                "NO"="darkred"))+xlab("Trial Temperature") + ylab("Count")
```

### Schedule

```{R echo = FALSE}
date_list <- data.frame(date = NA, trial = NA, period = NA)
date_list$date <- as.Date(date_list$date)
trial_list <- list("18", "20", "22", "24", "26")

for(a in 1:2){
  for(i in 1:length(trial_list)){
  holddf <- subset(original, original$Temperature == trial_list[i] & original$Period == a)
  dates <- unique(holddf$Date.x)
  for(j in 1:length(dates)){
    date_list[nrow(date_list) + 1,] <- list(dates[j], trial_list[i], a)
  }
}
}
date_list <- na.omit(date_list)

date_list$trial <- unlist(date_list$trial)
date_list$weekday <- weekdays(date_list$date)
date_list$month <- month(date_list$date)
date_list$day <- format(as.Date(date_list$date,format="%y-%m-%d"), format = "%d")

date_list$weekday <- as.factor(date_list$weekday)
date_list$month <- as.factor(date_list$month)
date_list$day <- as.factor(date_list$day)

date_list <- na.omit(date_list)
date_list$day <- as.numeric(as.character(date_list$day))  # "09" → 9
date_list$day <- factor(date_list$day, levels = 1:31)

ggplot(date_list, aes(x = day, y = as.factor(trial), fill = as.factor(period))) +
  geom_tile(color = "black",alpha = 0.5) +
  facet_wrap(~ month, ncol = 1) +
  coord_fixed() +
  scale_x_discrete(drop = FALSE)+
  ggtitle("Trial schedule for the Summer of 2025")+
  xlab("Day")+
  ylab("Trial Temperature")+ guides(fill=guide_legend(title="Period")) + theme_classic() +
  scale_fill_manual(values = c("1" = "red4",
                                "2"="blue4"))
```

### Size effect on Consumption

```{R echo = FALSE}
ggplot(censor, aes(x = WW, y = proportion.eaten, color = Species.x)) + geom_point() +geom_smooth(aes(x = WW, y = proportion.eaten,group = Species.x),   
    color = "black",    
    se = FALSE,
    inherit.aes = FALSE,
    method = "lm")+  
  scale_x_log10() +
  scale_color_manual(values = c("CI" = "darkorange",
                                "CM"="darkgreen",
                                "HS"="darkred")) + ylab("Amount Eaten (proportionally)") +xlab("WW (log scale)") +ggtitle("Amount Eaten by Weight (censor)") + labs(color = "Species")

ggplot(inclusive, aes(x = WW, y = proportion.eaten, color = Species.x)) + geom_point() +geom_smooth(aes(x = WW, y = proportion.eaten,group = Species.x),   
    color = "black",    
    se = FALSE,
    inherit.aes = FALSE,
    method = "lm")+  
  scale_x_log10() +
  scale_color_manual(values = c("CI" = "darkorange",
                                "CM"="darkgreen",
                                "HS"="darkred")) + ylab("Amount Eaten (proportionally)") +xlab("WW (log scale)") +ggtitle("Amount Eaten by Weight (inclusive)") + labs(color = "Species")
```

### Graphing the Husbandry Logs

```{R, echo = FALSE, warning = FALSE}
savedhus <- husbandry
husbandry <- savedhus
husbandry$Date <- as.Date(husbandry$Date, format="%m/%d/%Y")
ggplot(husbandry, aes(x = Date, y = as.numeric(Actual), color = as.factor(Temperature))) + geom_point() + facet_grid(Period~System)+
  scale_y_continuous(breaks = c(16, 18, 20, 22, 24, 26, 28))+ggtitle("Temperature Records for Each System and Trial") + 
  scale_color_manual(values = c("18"= "yellow",
                               "20" = "#fecc5c",
                               "22" = "#fd8d3c",
                               "24" ="#f03b20",
                               "26" = "#bd0026")) +theme_dark()
```

### Graphing Crab mass before and after the experiment

```{R, echo=FALSE,results='hide',fig.keep='all'}
ID_list <- list()
temperature_list <- list()
period_list <- list()
species_list <- list()
weight_before <- list()
weight_after <- list()

original_master <- na.omit(original_master)

for(i in 1:nrow(original_master)){
  if(original_master$ID[i] %in% deathMeta$ID){
    
  }
  else{
    ID_list <- append(ID_list, original_master$ID[i])
    temperature_list <- append(temperature_list, original_master$Temperature[i])
    period_list <- append(period_list, original_master$Period[i])
    species_list <- append(species_list, original_master$Species[i])
    weight_before <- append(weight_before, original_master$WW[i])
    weight_after <- append(weight_after, checkout$WW[which(checkout$ID == original_master$ID[i])])
  }
}

weight_df <- data.frame(
  ID = unlist(I(ID_list)),
  Temperature = unlist(I(temperature_list)),
  Period = unlist(I(period_list)),
  species = unlist(I(species_list)),
  weight_before = unlist(I(weight_before)),
  weight_after = unlist(I(weight_after))
)

weight_df$dif <- as.numeric(weight_df$weight_after) - as.numeric(weight_df$weight_before)

#CM139
#CM141

weight_df <- subset(weight_df, weight_df$ID != "CM139")
weight_df <- subset(weight_df, weight_df$ID != "CM141")

ggplot(weight_df, aes(x = as.factor(species), y = as.numeric(dif), fill = species)) + geom_boxplot(na.rm = TRUE)+
  scale_fill_manual(values = c("Carcinus" = "darkgreen",
                               "Hemigrapsus" = "darkred",
                               "Irroratus" = "darkorange"))+
  geom_hline(yintercept = 0, color = "red", linetype = "dashed", size = 0.5) + ggtitle("Weight change of each species over the whole experiment")+
  facet_wrap(~as.factor(Temperature))+xlab("Species") + ylab("Weight Change (g)")
```

Food effects

```{R}
ggplot(finalEatCensor, aes(x = Food, y = proportion.eaten, fill = Species.x)) + 
  geom_boxplot()+
  facet_grid(Period~as.factor(Temperature))

subcensor <- subset(finalEatCensor, finalEatCensor$Species.x == "CI")
mod <- glm(proportion.eaten ~ Food*Temperature + Period, data = subcensor)
par(mfrow = c(2,2))
plot(mod)
summary(mod)

subcensor <- subset(finalEatCensor, finalEatCensor$Species.x == "CM")
mod <- glm(proportion.eaten ~ Food*Temperature + Period, data = subcensor)
par(mfrow = c(2,2))
plot(mod)
summary(mod)

subcensor <- subset(finalEatCensor, finalEatCensor$Species.x == "HS")
mod <- glm(proportion.eaten ~ Food*Temperature + Period, data = subcensor)
par(mfrow = c(2,2))
plot(mod)
summary(mod)

```
