---
title: "ThesisStats"
author: "ChanceYan"
date: "2025-12-15"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{R, include = FALSE, warning = FALSE}
library(ggplot2)
library(lubridate)
library(hms)
library(dplyr)
library(AICcmodavg)
library(emmeans)
library(multcompView)
library(MuMIn)
library(nlme)
library(GGally)
library(DHARMa)
library(betareg)
setwd("/Users/chanceyan/Documents/R/ThesisCrab/Data")
crabdata <- read.csv("EditFeed.csv", h=T)
death <- read.csv("DeathCount.csv", h=T)
master <- read.csv("Master.csv", h=T)
deathMeta <- read.csv("Death.csv", h=T)
husbandry <- read.csv("Husbandry.csv", h=T)
checkout <- read.csv("CheckOut.csv", h=T)
```

```{R include = FALSE, warning = FALSE}
crabdata$FoodIn <- as.numeric(as.character(crabdata$FoodIn))
crabdata$FoodOut <- as.numeric(as.character(crabdata$FoodOut))

#removing rows that contain no data or recorded incorrectly
for(i in 1:nrow(crabdata)){
  if(!is.numeric(crabdata[i,4])){
    print(crabdata[i])
    crabdata <- crabdata[-i,]
  }
  if(!is.numeric(crabdata[i,6])){
    print(crabdata[i])
    crabdata <- crabdata[-i,]
  }
}



#Creating number IDs for each crab based of their IDs so it's easier to loop through with future code. Also I'm adding a total eaten by proportion column, so we have a standard metric to compare by.
for(i in 1:36){
  master$num[[i]] <- substr(master$ID[[i]], 3,5)
}

crabdata$amount.eaten <- crabdata$FoodIn-crabdata$FoodOut
all <- merge(crabdata, master, by="ID")

#Changing date column into a date data type, so that R can read it as a Date.
all$Date.x = as.Date(all$Date.x, format = "%m/%d/%Y")
deathMeta$Date = as.Date(deathMeta$Date, format = "%m/%d/%Y")

#removing mussel and mackerel feed
all <- subset(all, all$Food != "Mussels")
all <- subset(all, all$Food != "Mackerel")


#saving those who molted in an original dataset
original_molted <- all
original_molted$molted <- ifelse(grepl("ME", original_molted$Notes.x, fixed = TRUE), "YES", "NO")

#Removing those that molted
array <- c()

for(i in 1:nrow(all)){
  if(grepl("ME", all$Notes.x[i], fixed = TRUE)){
    ID_value <- all$ID[i]
    for(j in 1:nrow(all)){
      if(all$ID[j] == ID_value){
        array <- c(array, j)
      }
    }
  }
}

all <- all[-array,]
array <- c()

#Removing these dates because feeding was not following a strict schedule (fed two days back to back)
all <- subset(all, !(WeekNum == 1 & Trial.x == 16))
all <- subset(all, !(WeekNum == 1 & Trial.x == 22 & Period == 1))

#Changing trials 16 and 18 to be one.
original <- all
all$Trial.x <- ifelse(all$Trial.x == "16", "18", all$Trial.x)
original$Trial.x <- ifelse(original$Trial.x == "16", "18", original$Trial.x)
master$Trial <- ifelse(master$Trial == "16", "18", master$Trial)

#Here, I am marking all those who did not eat
EatDF <- subset(all, grepl("DE", all$Notes.x, fixed = TRUE))

#removing all those who ate everything
all <- all[ !grepl("AE", all$Notes.x), ]

#removing all those who were found to have floating food
all <- all[ !grepl("FLOAT", all$Notes.x), ]

#Making a new column indicating whether the animal ate or not
eaten_row <- list()
for(i in 1:nrow(all)){
  if(grepl("DE", all$Notes.x[i], fixed = TRUE)){
    eaten_row <- c(eaten_row, "NO")
  }
  else{
    eaten_row <- c(eaten_row, "YES")
  }
}
all$eaten <- eaten_row

#Making a column if the animal was still eating or not
all$still_eating <- ifelse(grepl("SE", all$Notes.x, fixed = TRUE), "YES", "NO")

inBucket <- list()
#total time of food in bucket
all$TimeInStrip <- as.POSIXct(paste(all$Date.x, all$TimeIn), format = "%Y-%m-%d %I:%M:%S %p")
all$TimeOutStrip <- as.POSIXct(paste(all$Date.x, all$TimeOut), format = "%Y-%m-%d %I:%M:%S %p")

#because we removed the first week from trials 1 and 2, to get the final week, I'll just subtract one from the value to line it up so that week 4 equals week 3 and make it easier for me to graph

all$WeekNum <- ifelse((all$Trial.x == "18" & all$WeekNum == 2 & all$Period == 1), "1", all$WeekNum)
all$WeekNum <- ifelse((all$Trial.x == "18" & all$WeekNum == 3 & all$Period == 1), "2", all$WeekNum)
all$WeekNum <- ifelse((all$Trial.x == "18" & all$WeekNum == 4 & all$Period == 1), "3", all$WeekNum)

all$WeekNum <- ifelse((all$Trial.x == "22" & all$WeekNum == 2 & all$Period == 1), "1", all$WeekNum)
all$WeekNum <- ifelse((all$Trial.x == "22" & all$WeekNum == 3 & all$Period == 1), "2", all$WeekNum)
all$WeekNum <- ifelse((all$Trial.x == "22" & all$WeekNum == 4 & all$Period == 1), "3", all$WeekNum)

#husbandry sheet prep
husbandry <- subset(husbandry, husbandry$Trial != "NONE")
```

BINARY dead or alive (one off - is not affected by removal or replacement of dead crabs)
```{R}
#parsing between those who died during the experiment and those who lived
master$dead <- ifelse(master$ID %in% deathMeta$ID, 0, 1)	

#addition of extras
add_rows <- data.frame(ID = "extra1", System = NA, CL = NA, WW = NA, Trial = "26", Species = "Irroratus", Condition = NA, Period = NA, Date = NA, Notes = NA, num = NA, dead = 0)
master <- rbind(master, add_rows)
add_rows <- data.frame(ID = "extra2", System = NA, CL = NA, WW = NA, Trial = "26", Species = "Irroratus", Condition = NA, Period = NA, Date = NA, Notes = NA, num = NA, dead = 0)
master <- rbind(master, add_rows)
add_rows <- data.frame(ID = "extra3", System = NA, CL = NA, WW = NA, Trial = "24", Species = "Irroratus", Condition = NA, Period = NA, Date = NA, Notes = NA, num = NA, dead = 0)
add_rows <- data.frame(ID = "extra3", System = NA, CL = NA, WW = NA, Trial = "24", Species = "Irroratus", Condition = NA, Period = NA, Date = NA, Notes = NA, num = NA, dead = 1)
add_rows <- data.frame(ID = "extra3", System = NA, CL = NA, WW = NA, Trial = "22", Species = "Irroratus", Condition = NA, Period = NA, Date = NA, Notes = NA, num = NA, dead = 1)
add_rows <- data.frame(ID = "extra3", System = NA, CL = NA, WW = NA, Trial = "22", Species = "Irroratus", Condition = NA, Period = NA, Date = NA, Notes = NA, num = NA, dead = 1)
add_rows <- data.frame(ID = "extra3", System = NA, CL = NA, WW = NA, Trial = "20", Species = "Irroratus", Condition = NA, Period = NA, Date = NA, Notes = NA, num = NA, dead = 1)
add_rows <- data.frame(ID = "extra3", System = NA, CL = NA, WW = NA, Trial = "20", Species = "Irroratus", Condition = NA, Period = NA, Date = NA, Notes = NA, num = NA, dead = 1)
add_rows <- data.frame(ID = "extra3", System = NA, CL = NA, WW = NA, Trial = "18", Species = "Irroratus", Condition = NA, Period = NA, Date = NA, Notes = NA, num = NA, dead = 1)
add_rows <- data.frame(ID = "extra3", System = NA, CL = NA, WW = NA, Trial = "18", Species = "Irroratus", Condition = NA, Period = NA, Date = NA, Notes = NA, num = NA, dead = 1)
master <- rbind(master, add_rows)

all.mod <- glm(dead ~ Trial*Species, family = binomial, data = master, na.action = "na.fail")
dredge(all.mod, rank = "AIC")

best.mod <- glm(dead ~ Trial + Species, family = binomial, data = master, na.action = "na.fail")

res <- simulateResiduals(best.mod)
plot(res)
testDispersion(res)

emm <- emmeans(best.mod, ~ Trial | Species)
pairs(emm)

#just looking at cancer irroratus since HS and CM have very little deaths
#dropping trials and species that have 0 deaths gives us something to work with
holddf <- subset(master, master$Species == "Irroratus" & master$Trial != 18)

mod <-  glm(dead ~ Trial, family = binomial, data = holddf, na.action = "na.fail")
summary(mod)
plot(mod)

res <- simulateResiduals(mod)
plot(res)
testDispersion(res)

emm <- emmeans(mod, ~ Trial)
pairs(emm)


```

RUN THIS FOR 1
DROPPING ALL THOSE WHO DIED AND WERE REPLACED
```{R}
all$proportion.eaten <- all$amount.eaten / all$WW

all <- all[ !is.na(all$ID) & !(all$ID %in% deathMeta$ID), ]

all <- subset(all, !is.na(all$proportion.eaten))
```

RUN THIS FOR 2
KEEPING ALL THOSE WHO DIED (EVERYTHING BEFORE DEATH, AND THE data collected by the REPLACED WITH NEW CRABS)
```{R}
all <- all %>%
  filter(!grepl("ADDI", Notes.x))

all <- all %>%
  filter(!grepl("DI", Notes.x))

#This method accounts for the crabs who died and adds crabs who were replaced after
#run through the feed data
for(i in 1:nrow(all)){
  if(!is.na(all$Date.x[i])){
      #if the individual is marked on the death metasheet then that means they may have been replaced (or not)
    if(any(deathMeta$ID == all$ID[i])){
      #If the ID is on the death metasheet, check which row it's on and see if it's been replaced or not
      row_dat <- deathMeta[deathMeta$ID == all$ID[i],]
      #the value has been replaced!
      if(row_dat$Replaced == "Y"){
        #Only replace if date is after the death date
        if(all$Date.x[i] >= row_dat$Date){
          all$proportion.eaten[i] <- all$amount.eaten[i] / row_dat$ReplacedWeight
          all$WW[i] <- row_dat$ReplacedWeight
        }
        else{
          all$proportion.eaten[i] <- (all$amount.eaten[i] / all$WW[i])
        }
      }
      #If not replaced continue as usual
      else{
        all$proportion.eaten[i] <- (all$amount.eaten[i] / all$WW[i])
      }
    }
    #If not on death sheet continue as usual
    else{
      all$proportion.eaten[i] <- (all$amount.eaten[i] / all$WW[i])
    }
  }
  else{
    all$proportion.eaten[i] <- (all$amount.eaten[i] / all$WW[i])
  }
}

all <- subset(all, !is.na(all$proportion.eaten))
```

KEEP FOR 3
KEEPING ALL THOSE WHO DIED (before death) AND REMOVE THE REPLACED ONES
```{R}
#nothing
all <- all %>%
  filter(!grepl("ADDI", Notes.x))

all <- all %>%
  filter(!grepl("RE", Notes.x))

all <- all %>%
  filter(!grepl("DI", Notes.x))

all$proportion.eaten <- all$amount.eaten / all$WW

all <- subset(all, !is.na(all$proportion.eaten))
```

KEEP FOR 4
DEAD BECOMES 0'S - do not remove "DIs", need to make the actual death (recheck data sheet later), removal of the replaced ones
```{R}
all <- all %>%
  filter(!grepl("RE", Notes.x))

all$proportion.eaten <- all$amount.eaten / all$WW

all <- subset(all, !is.na(all$proportion.eaten))
```


PUSHING THOSE WHO Didn't eat TO 0 (AS OPPOSED TO JUST LEAVING IT) and making values that are negative, 0 or positive
```{R}
#pushing all those who did not eat to 0, rather than keeping them at value
#set to 0.01 rather than 0 for the stats transformation
all$proportion.eaten <- ifelse(grepl("DE", all$Notes.x, fixed = TRUE), 0.01, all$proportion.eaten)
all$proportion.eaten <- ifelse(all$proportion.eaten < 0, 0.01, all$proportion.eaten)

all$proportion.eaten <- ifelse(grepl("DE", all$Notes.x, fixed = TRUE), 0, all$proportion.eaten)
all$proportion.eaten <- ifelse(all$proportion.eaten < 0, 0, all$proportion.eaten)
all$amount.eaten <- ifelse(grepl("DE", all$Notes.x, fixed = TRUE), 0, all$amount.eaten)
```

DEAD REMOVALS
```{R}
for(i in 1:nrow(all)){
  if(grepl("DI", all$Notes.x[i], fixed = TRUE)){
    all <- all[-i, ] 
  }
  if(is.na(all$amount.eaten[i])){
    all <- all[-i,]
  }
}
```

Acclimation effects
```{R}
summary_df <- all %>%
  group_by(Species.x, Trial.x, Period, WeekNum) %>%
  summarise(
    mean = mean(proportion.eaten),
    se = sd(proportion.eaten) / sqrt(n())
  )

holddf <- subset(summary_df, summary_df$Species.x == "CI")

ggplot(holddf, aes(x = as.numeric(WeekNum), y = mean, color = as.factor(Period))) + 
  geom_point(position = position_dodge(width = 0.2)) + 
  facet_wrap(~Trial.x) +
  ggtitle("Proportion consumed over time for Period 1+2, Rock Crab") + 
  geom_smooth(method = "loess", se = FALSE)+
  scale_color_manual(values = c("1" = "red4","2"="blue4"))+
  xlab("Week Number") + 
  ylab("Amount Eaten (Proportionally)") + 
  labs(color = "Period")+
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), position = position_dodge(width = 0.2))

holddf <- subset(summary_df, summary_df$Species.x == "CM")

ggplot(holddf, aes(x = as.numeric(WeekNum), y = mean, color = as.factor(Period))) + 
  geom_point(position = position_dodge(width = 0.2)) + 
  facet_wrap(~Trial.x) +
  ggtitle("Proportion consumed over time for Period 1+2, Green Crab") + 
  geom_smooth(method = "loess", se = FALSE)+
  scale_color_manual(values = c("1" = "red4","2"="blue4"))+
  xlab("Week Number") + 
  ylab("Amount Eaten (Proportionally)") + 
  labs(color = "Period")+
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), position = position_dodge(width = 0.2))

holddf <- subset(summary_df, summary_df$Species.x == "HS")

ggplot(holddf, aes(x = as.numeric(WeekNum), y = mean, color = as.factor(Period))) + 
  geom_point(position = position_dodge(width = 0.2)) + 
  facet_wrap(~Trial.x) +
  ggtitle("Proportion consumed over time for Period 1+2, Asian Shore Crab") + 
  geom_smooth(method = "loess", se = FALSE)+
  scale_color_manual(values = c("1" = "red4","2"="blue4"))+
  xlab("Week Number") + 
  ylab("Amount Eaten (Proportionally)") + 
  labs(color = "Period")+
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), position = position_dodge(width = 0.2))

#plotting differences for CI - we only care about differences within species not across
holddf <- subset(all, all$Species.x == "CI")

models <- list()
models[[1]] <- glm(proportion.eaten ~ 1, data = holddf)
models[[2]] <- glm(proportion.eaten ~ as.factor(Trial.x)*as.factor(WeekNum)*as.factor(Period), data = holddf)
models[[3]] <- glm(proportion.eaten ~ as.factor(Trial.x)*as.factor(WeekNum), data = holddf)
models[[4]] <- glm(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = holddf)
models[[5]] <- glm(proportion.eaten ~ as.factor(Trial.x)*as.factor(Period), data = holddf)
models[[6]] <- glm(proportion.eaten ~ as.factor(Trial.x), data = holddf)
models[[7]] <- glm(proportion.eaten ~ as.factor(Period), data = holddf)
models[[8]] <- glm(proportion.eaten ~ as.factor(WeekNum), data = holddf)
models[[9]] <- glm(proportion.eaten ~ as.factor(Trial.x)+as.factor(WeekNum)+as.factor(Period), data = holddf)
models[[10]] <- glm(proportion.eaten ~ as.factor(Trial.x)+as.factor(WeekNum), data = holddf)
models[[11]] <- glm(proportion.eaten ~ as.factor(WeekNum)+as.factor(Period), data = holddf)
models[[12]] <- glm(proportion.eaten ~ as.factor(Trial.x)+as.factor(Period), data = holddf)
models[[13]] <- glm(proportion.eaten ~ as.factor(Trial.x)+as.factor(WeekNum)*as.factor(Period), data = holddf)
models[[14]] <- glm(proportion.eaten ~ as.factor(Trial.x)*as.factor(WeekNum)+as.factor(Period), data = holddf)
models[[15]] <- glm(proportion.eaten ~ as.factor(Trial.x)*as.factor(Period)+as.factor(WeekNum), data = holddf)

aictab(models)
#because the model spits back factor as an additive function, we can assume weeknum has an effect
#on proportion consumed, but does not vary across Period or Trial

holddf <- subset(all, all$Species.x == "CI")
mod <- glm(proportion.eaten ~ as.factor(Trial.x)*as.factor(Period)+as.factor(WeekNum), data = holddf)

plot(mod)

emm <- emmeans(mod, ~ as.factor(WeekNum))
pairs(emm, simple = "WeekNum")
cld_df <- as.data.frame(
  multcomp::cld(emm, Letters = letters, adjust = "tukey")
)
ggplot(cld_df, aes(x = WeekNum, y = emmean, fill = WeekNum)) +
  geom_col(position = position_dodge(width = 0.9)) +
  geom_text(
    aes(label = .group),
    position = position_dodge(width = 0.9),
    vjust = -0.4,
    size = 5
  ) +
  labs(
    x = "Trial",
    y = "Proportion Eaten"
  ) +
  theme_classic() +
  theme(
    legend.position = "top"
  )+
  scale_fill_manual(values = c("1" = "darkorange",
                                "2"="darkgreen",
                                "3"="darkred"))+ coord_cartesian(ylim = c(0, max(cld_df$emmean) * 1.15))
#CI week 1 and 3 are the same and week 2 and 3 are the same; however, 
#week 1 and 2 are not the same
#--------------------------CM---------------------------
holddf <- subset(all, all$Species.x == "CM")

models <- list()
models[[1]] <- glm(proportion.eaten ~ 1, data = holddf)
models[[2]] <- glm(proportion.eaten ~ as.factor(Trial.x)*as.factor(WeekNum)*as.factor(Period), data = holddf)
models[[3]] <- glm(proportion.eaten ~ as.factor(Trial.x)*as.factor(WeekNum), data = holddf)
models[[4]] <- glm(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = holddf)
models[[5]] <- glm(proportion.eaten ~ as.factor(Trial.x)*as.factor(Period), data = holddf)
models[[6]] <- glm(proportion.eaten ~ as.factor(Trial.x), data = holddf)
models[[7]] <- glm(proportion.eaten ~ as.factor(Period), data = holddf)
models[[8]] <- glm(proportion.eaten ~ as.factor(WeekNum), data = holddf)
models[[9]] <- glm(proportion.eaten ~ as.factor(Trial.x)+as.factor(WeekNum)+as.factor(Period), data = holddf)
models[[10]] <- glm(proportion.eaten ~ as.factor(Trial.x)+as.factor(WeekNum), data = holddf)
models[[11]] <- glm(proportion.eaten ~ as.factor(WeekNum)+as.factor(Period), data = holddf)
models[[12]] <- glm(proportion.eaten ~ as.factor(Trial.x)+as.factor(Period), data = holddf)
models[[13]] <- glm(proportion.eaten ~ as.factor(Trial.x)+as.factor(WeekNum)*as.factor(Period), data = holddf)
models[[14]] <- glm(proportion.eaten ~ as.factor(Trial.x)*as.factor(WeekNum)+as.factor(Period), data = holddf)
models[[15]] <- glm(proportion.eaten ~ as.factor(Trial.x)*as.factor(Period)+as.factor(WeekNum), data = holddf)

aictab(models)

holddf <- subset(all, all$Species.x == "CM")
mod <- glm(proportion.eaten ~ as.factor(Trial.x)*as.factor(Period)+as.factor(WeekNum), data = holddf)

plot(mod)

emm <- emmeans(mod, ~ as.factor(WeekNum))
pairs(emm, simple = "WeekNum")
cld_df <- as.data.frame(
  multcomp::cld(emm, Letters = letters, adjust = "tukey")
)
ggplot(cld_df, aes(x = WeekNum, y = emmean, fill = WeekNum)) +
  geom_col(position = position_dodge(width = 0.9)) +
  geom_text(
    aes(label = .group),
    position = position_dodge(width = 0.9),
    vjust = -0.4,
    size = 5
  ) +
  labs(
    x = "Trial",
    y = "Proportion Eaten"
  ) +
  theme_classic() +
  theme(
    legend.position = "top"
  )+
  scale_fill_manual(values = c("1" = "darkorange",
                                "2"="darkgreen",
                                "3"="darkred"))+ coord_cartesian(ylim = c(0, max(cld_df$emmean) * 1.15))
#CM all the same
#---------------------------------------HS------------------------------------
holddf <- subset(all, all$Species.x == "HS")

models <- list()
models[[1]] <- glm(proportion.eaten ~ 1, data = holddf)
models[[2]] <- glm(proportion.eaten ~ as.factor(Trial.x)*as.factor(WeekNum)*as.factor(Period), data = holddf)
models[[3]] <- glm(proportion.eaten ~ as.factor(Trial.x)*as.factor(WeekNum), data = holddf)
models[[4]] <- glm(proportion.eaten ~ as.factor(WeekNum)*as.factor(Period), data = holddf)
models[[5]] <- glm(proportion.eaten ~ as.factor(Trial.x)*as.factor(Period), data = holddf)
models[[6]] <- glm(proportion.eaten ~ as.factor(Trial.x), data = holddf)
models[[7]] <- glm(proportion.eaten ~ as.factor(Period), data = holddf)
models[[8]] <- glm(proportion.eaten ~ as.factor(WeekNum), data = holddf)
models[[9]] <- glm(proportion.eaten ~ as.factor(Trial.x)+as.factor(WeekNum)+as.factor(Period), data = holddf)
models[[10]] <- glm(proportion.eaten ~ as.factor(Trial.x)+as.factor(WeekNum), data = holddf)
models[[11]] <- glm(proportion.eaten ~ as.factor(WeekNum)+as.factor(Period), data = holddf)
models[[12]] <- glm(proportion.eaten ~ as.factor(Trial.x)+as.factor(Period), data = holddf)
models[[13]] <- glm(proportion.eaten ~ as.factor(Trial.x)+as.factor(WeekNum)*as.factor(Period), data = holddf)
models[[14]] <- glm(proportion.eaten ~ as.factor(Trial.x)*as.factor(WeekNum)+as.factor(Period), data = holddf)
models[[15]] <- glm(proportion.eaten ~ as.factor(Trial.x)*as.factor(Period)+as.factor(WeekNum), data = holddf)

aictab(models)

holddf <- subset(all, all$Species.x == "HS")
mod <- glm(proportion.eaten ~ as.factor(Trial.x)*as.factor(Period) + as.factor(WeekNum), data = holddf)

plot(mod)

emm <- emmeans(mod, ~ as.factor(WeekNum))
pairs(emm, simple = "WeekNum")
cld_df <- as.data.frame(
  multcomp::cld(emm, Letters = letters, adjust = "tukey")
)
ggplot(cld_df, aes(x = WeekNum, y = emmean, fill = WeekNum)) +
  geom_col(position = position_dodge(width = 0.9)) +
  geom_text(
    aes(label = .group),
    position = position_dodge(width = 0.9),
    vjust = -0.4,
    size = 5
  ) +
  labs(
    y = "Proportion Eaten"
  ) +
  theme_classic() +
  theme(
    legend.position = "top"
  )+
  scale_fill_manual(values = c("1" = "darkorange",
                                "2"="darkgreen",
                                "3"="darkred"))+ coord_cartesian(ylim = c(0, max(cld_df$emmean) * 1.15))
#Week 1 and 2 are equal; however, week 3 is not equal to 1 or 2...
```

ANOVA differences between proportion eaten between species and trial

-Use proportion eaten as response variable -> Beta Regression
-Use amount eaten and add WW as a factor (random...?)

```{R}
all <- subset(all, all$WeekNum != 1)
all <- subset(all, all$WeekNum != 2)

# Keep all columns, remove rows with NA in selected columns
all <- all[!is.na(all$proportion.eaten) &
                 !is.na(all$Species.x) &
                 !is.na(all$Trial.x) &
                 !is.na(all$WW), ]


#very Right skewed response variables - try transforming them?
#skewed because it's a proportion! Therefore binomial!
hist(all$proportion.eaten)

#to transform need to set all those who did eat to 0
all$proportion.eaten <- ifelse(grepl("DE", all$Notes.x, fixed = TRUE), 0.01, all$proportion.eaten)
all$proportion.eaten <- ifelse(all$proportion.eaten < 0, 0.01, all$proportion.eaten)
all$prop_log <- log(all$proportion.eaten)
hist(all$prop_log)

#USING PROPOTION EATEN WITH GAMMA FAMILY-----------------------------------------------------
all.mod.gamma <- glm(proportion.eaten ~ Period*Species.x*Trial.x, family = Gamma(link="log"), data = all, na.action = "na.fail")
dredge(all.mod.gamma, rank = "AIC")
best.mod.gamma <- glm(proportion.eaten ~ Period + Species.x + Trial.x +
                        Period*Trial.x + Species.x*Trial.x, family = Gamma(link="log"), data = all)

res <- residuals(best.mod.gamma)
hist(res)
library(DHARMa)
sim <- simulateResiduals(best.mod.gamma)
plot(sim)
plot(all.mod.gamma)

library(boot)
mod.diag <- glm.diag(all.mod.gamma)
glm.diag.plots(all.mod.gamma, mod.diag)

all.mod.gammaidentity <- glm(proportion.eaten ~ Period*Species.x*Trial.x, family = Gamma(link = "identity"), data = all, na.action = "na.fail")
dredge(all.mod.gammaidentity, rank = "AIC")
best.mod.gamma.identity <- glm(proportion.eaten ~ Species.x*Trial.x, family = Gamma(link = "identity"), data = all)
res <- residuals(best.mod.gamma.identity)
hist(res)
library(DHARMa)
sim <- simulateResiduals(best.mod.gamma.identity)
plot(sim)
plot(best.mod.gamma.identity)

library(boot)
mod.diag <- glm.diag(best.mod.gamma.identity)
glm.diag.plots(best.mod.gamma.identity, mod.diag)

all.mod <- glm(proportion.eaten ~ Period*Species.x*Trial.x, family = Gamma(link = "inverse"), data = all, na.action = "na.fail")
dredge(all.mod)
best.mod <- glm(proportion.eaten ~ Period + Species.x + Trial.x + Period*Trial.x + Species.x*Trial.x, family = Gamma(link = "inverse"), data = all)
plot(best.mod)
hist(best.mod$residuals)
summary(best.mod)
mod.diag <- glm.diag(best.mod)
glm.diag.plots(best.mod, mod.diag)
sim <- simulateResiduals(best.mod)
plot(sim)

#subsetting by species-------------------------------------------------------

holddf <- subset(all, all$Species.x == "CI")
all.mod <- glm(proportion.eaten ~ Period*Trial.x, family = Gamma(link = "inverse"), data = holddf, na.action = "na.fail")
dredge(all.mod)
best.mod <- glm(proportion.eaten ~ Trial.x, family = Gamma(link = "inverse"), data = holddf)
plot(best.mod)
hist(best.mod$residuals)
summary(best.mod)
mod.diag <- glm.diag(best.mod)
glm.diag.plots(best.mod, mod.diag)
sim <- simulateResiduals(best.mod)
plot(sim)

#BETA REGRESSION--------------------------------------------------------------------
models <- list()
#since betaregression can't handle 0's...
#just add 0.5 to all values lol
all$proportion.eaten.weight <- all$proportion.eaten + 0.5

models[[1]] <- betareg(proportion.eaten.weight ~ Species.x*as.factor(Trial.x)*as.factor(Period), data = all, link = "logit", na.action = "na.fail")
models[[2]] <- betareg(proportion.eaten.weight ~ Species.x+as.factor(Trial.x)+as.factor(Period), data = all, link = "logit", na.action = "na.fail")
models[[3]] <- betareg(proportion.eaten.weight ~ Species.x*as.factor(Trial.x)+as.factor(Period), data = all, link = "logit", na.action = "na.fail")
models[[4]] <- betareg(proportion.eaten.weight ~ Species.x+as.factor(Trial.x)*as.factor(Period), data = all, link = "logit", na.action = "na.fail")
models[[5]] <- betareg(proportion.eaten.weight ~ Species.x*as.factor(Period)+as.factor(Trial.x), data = all, link = "logit", na.action = "na.fail")

aictab(models)

best.mod <- betareg(proportion.eaten.weight ~ Species.x*as.factor(Trial.x)*as.factor(Period) | Species.x, data = all, link = "logit", na.action = "na.fail")

res <- residuals(best.mod, type = "pearson")
fitted <- fitted(best.mod)

plot(fitted, res,
     xlab = "Fitted values",
     ylab = "Pearson residuals")
abline(h = 0, col = "red")

qres <- residuals(best.mod, type = "quantile")
qqnorm(qres)
qqline(qres)

var(residuals(best.mod, type = "pearson"))


emm <- emmeans(
  best.mod,
  ~ Species.x * Trial.x * Period,
  type = "response"   # IMPORTANT
)
emm


cld_df <- as.data.frame(
  multcomp::cld(emm, Letters = letters, adjust = "tukey")
)



#QUASIBINOMIAL----------------------------------------------------------------------------------
#fitting a binomial with a logit link - set the values to 0 (those that are negative)
models <- list()

models[[1]] <- glm(proportion.eaten ~ 1, data = all, family = quasibinomial("logit"), na.action = "na.fail")
models[[2]] <- glm(proportion.eaten ~ Species.x*as.factor(Trial.x)*as.factor(Period), data = all, family = quasibinomial("logit"), na.action = "na.fail")
models[[3]] <- glm(proportion.eaten ~ Species.x+as.factor(Trial.x)+as.factor(Period), data = all, family = quasibinomial("logit"), na.action = "na.fail")
models[[4]] <- glm(proportion.eaten ~ Species.x+as.factor(Trial.x)*as.factor(Period), data = all, family = quasibinomial("logit"), na.action = "na.fail")
models[[5]] <- glm(proportion.eaten ~ Species.x*as.factor(Trial.x)+as.factor(Period), data = all, family = quasibinomial("logit"), na.action = "na.fail")
models[[6]] <- glm(proportion.eaten ~ as.factor(Trial.x)+as.factor(Period)*Species.x, data = all, family = quasibinomial("logit"), na.action = "na.fail")
models[[7]] <- glm(proportion.eaten ~ as.factor(Period)*Species.x, data = all, family = quasibinomial("logit"), na.action = "na.fail")
models[[8]] <- glm(proportion.eaten ~ as.factor(Period)+Species.x, data = all, family = quasibinomial("logit"), na.action = "na.fail")
models[[9]] <- glm(proportion.eaten ~ as.factor(Period)*Trial.x, data = all, family = quasibinomial("logit"), na.action = "na.fail")
models[[10]] <- glm(proportion.eaten ~ as.factor(Period)+Trial.x, data = all, family = quasibinomial("logit"), na.action = "na.fail")
models[[11]] <- glm(proportion.eaten ~ Species.x*Trial.x, data = all, family = quasibinomial("logit"), na.action = "na.fail")
models[[12]] <- glm(proportion.eaten ~ Species.x+Trial.x, data = all, family = quasibinomial("logit"), na.action = "na.fail")
models[[13]] <- glm(proportion.eaten ~ Species.x, data = all, family = quasibinomial("logit"), na.action = "na.fail")
models[[14]] <- glm(proportion.eaten ~ Trial.x, data = all, family = quasibinomial("logit"), na.action = "na.fail")
models[[15]] <- glm(proportion.eaten ~ Period, data = all, family = quasibinomial("logit"), na.action = "na.fail")

aictab(models)

hist(allmod$residuals)
plot(allmod)

#WW AS A FACTOR---------------------------------------------------------------------------
#best model via AIC
best.mod <- glm(proportion.eaten ~ Species.x * as.factor(Trial.x) * WW, data = all)
plot(best.mod)
hist(best.mod$residuals)

#Using total amount eaten and adding WW as a factor
all.mod <- glm(amount.eaten ~ Species.x * as.factor(Trial.x) * WW * Period, data = all)
dredge(all.mod, rank = "AIC")

best_model <- glm(
  amount.eaten ~
    as.factor(Trial.x) * Period * Species.x +
    WW * Period +
    WW * as.factor(Trial.x) +
    WW * Species.x,
  data = all
)


plot(best_model)
hist(best_model$residuals)
summary(best_model)

#violating constantance of variance rule

#transform amount eaten to see if it makes it better
hist(all$amount.eaten)
all$amount.eaten <- ifelse(all$amount.eaten < 0, 0, all$amount.eaten)
all$amount.eaten.trans <- log(all$amount.eaten + 1)
hist(all$amount.eaten.trans)

#when dividing up the individual species, you can see it follows an almost normal pattern with a large influx of 0's (didn't eat or dead)
holddf <- subset(all, all$Species.x == "HS")
all.mod <- glm(amount.eaten.trans ~  as.factor(Trial.x) * WW * Period, data = holddf)
hist(holddf$amount.eaten.trans)
holddf <- subset(all, all$Species.x == "CM")
all.mod <- glm(amount.eaten.trans ~  as.factor(Trial.x) * WW * Period, data = holddf)
hist(holddf$amount.eaten.trans)
holddf <- subset(all, all$Species.x == "CI")
all.mod <- glm(amount.eaten.trans ~  as.factor(Trial.x) * WW * Period, data = holddf)
hist(holddf$amount.eaten.trans)

dredge(all.mod, rank = "AIC")

best_model <- glm(
  amount.eaten.trans ~
    as.factor(Trial.x) * Period * Species.x +
    WW * Period +
    WW * as.factor(Trial.x) +
    WW * Species.x,
  data = all
)

plot(best_model)

#GLS stuff-------------------------------------------------------------------------------
models <- list()
models[[1]] <- gls(proportion.eaten ~ Species.x * factor(Trial.x) * WW,
             weights = varPower(form = ~fitted(.)),
             data = all,
             na.action = na.omit)
models[[2]] <- gls(proportion.eaten ~ Species.x * factor(Trial.x),
             weights = varPower(form = ~fitted(.)),
             data = all,
             na.action = na.omit)
models[[3]] <- gls(proportion.eaten ~ Species.x * factor(Trial.x) * Period,
             weights = varPower(form = ~fitted(.)),
             data = all,
             na.action = na.omit)
models[[4]] <- gls(proportion.eaten ~ Species.x * factor(Trial.x) + Period,
             weights = varPower(form = ~fitted(.)),
             data = all,
             na.action = na.omit)
models[[5]] <- gls(proportion.eaten ~ 1,
             weights = varPower(form = ~fitted(.)),
             data = all,
             na.action = na.omit)
names(models) <- c("STW","ST", "STP", "STPR", "Null")
aictab(models)

mod <- gls(proportion.eaten ~ Species.x * factor(Trial.x) + Period,
             weights = varPower(form = ~fitted(.)),
             data = all,
             na.action = na.omit)

# Standardized residuals
resid_std <- resid(mod, type = "normalized")  # or "pearson"

# Fitted values
fitted_vals <- fitted(mod)


qqnorm(resid_std)
qqline(resid_std, col = "red")

summary(mod)
```

Time BS
```{R}
#times are NA on this individual
for(i in 1:nrow(all)){
  if(is.na(all$TimeInStrip[i])){
    all <- all[-i,]
  }
}

#all$TimeOut <- hm(all$TimeOut)
for(i in 1:nrow(all)){
  hour <- as.numeric(format(all$TimeInStrip[i], "%H"))
  if(hour < 8){
    #print(all$TimeInStrip[i])
    all$TimeInStrip[i] <- all$TimeInStrip[i] + 12 * 60 * 60
  }
  hour <- as.numeric(format(all$TimeOutStrip[i], "%H"))
  if(hour < 8){
    #print(all$TimeInStrip[i])
    all$TimeOutStrip[i] <- all$TimeOutStrip[i] + 12 * 60 * 60
  }
  
  inBucket <- append(inBucket, as.numeric(difftime(all$TimeOutStrip[i], all$TimeInStrip[i], units = "mins")))
}

all$timeInBucket <- inBucket

all$timebucketnum <- as.numeric(all$timeInBucket)

#to calculate feeding rate based on time in bucket - we need to make amounts more than 0 or 0
all$hours <- all$timebucketnum / 60
all$rate <- all$proportion.eaten / all$hours


```

Things I found:
-Slight changes when switching between the 4 options (nothing signfiicant, graphs look slightly better for some CI)
-for pushing DEs and DIs to 0, there is very little to no change
-For NN2, adding week 2 and 3 into the proportion eaten model does not change much (some letter changes)

Questions:
-If I've added proportion eaten as part of the model (which is based on weight), do I need to add weight as an explanatory variable? When using ggpairs, there is correlation between Wet weight and proportion eaten (expected). AIC outputs it's a better model?
-Do we use GLMs because sometimes there isn't a normal distribution?
-Acclimation: should we trust the AIC return and models? AIC returns no interaction with WeekNum (doesn't change across Trial and Period for ALL species). Model diagnostic plots look good. Only concern - looks different when plotting out means and SE

